<?php
/* @var $this Mirasvit_Rma_Block_Rma_New_Step2 */
?>
<div class="rma-new-step2">
    <div class="page-title">
        <h1><?php echo $this->__('Request New Return') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getStep2PostUrl()?>" method="POST" enctype="multipart/form-data" id="rma-form-validate" >
        <?php echo $this->getBlockHtml('formkey')?>
        <input name="form_uid" type="hidden" value="<?php echo rand(1, 1000) ?>">

        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Enter information for each item') ?></h2>
        </div>
        <?php if ($this->getAllowGift()): ?>
            <?php echo $this->getChildHtml('rma.new.gift') ?>
        <?php endif?>

        <table width="100%">
            <thead>
                <tr>
                    <th class="no-wrap"></th>
                    <th class="no-wrap">
                        <?php echo $this->__('Product Name') ?>
                    </th class="no-wrap">
                    <th class="no-wrap">
                        <?php echo $this->__('Qty') ?>
                    </th>
                    <th class="no-wrap">
                        <?php echo $this->__('Order') ?>
                    </th>
                    <th class="no-wrap"></th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->getChildHtml('rma.order.list') ?>
                <?php echo $this->getChildHtml('rma.offline.order.list') ?>
            </tbody>
        </table>


        <div class="clearfix"></div>

        <?php
        $customFields = $this->getCustomFields();
        if ($customFields->count()):
        ?>
            <div class="fieldset">
                <ul class="form-list">
                    <?php foreach ($customFields as $field): ?>
                    <li class="control">
                        <label id="customer-field" for="<?php echo $field->getCode()?>" <?php echo $field->getIsRequiredCustomer() ? 'class="required"><em>*</em>' : '>'?><?php echo $this->__($field->getName()) ?></label>
                        <?php echo Mage::helper('rma/field')->getInputHtml($field)?>
                        <p id="user-description"><?php echo $field->getDescription() ?></p>
                    </li>
                    <?php endforeach ?>
                </ul>
            </div>
        <?php endif ?>

        <div class="fieldset">
            <h2 class="legend" id="additional-information"><?php echo $this->__('Additional Information') ?></h2>
            <ul class="form-list">
                <li class="wide">
                    <div class="input-box">
                        <textarea name="comment" id="comment" class="input-text"></textarea>
                    </div>
                </li>
                <li class="wide">
                    <label for="attachment"><?php echo $this->__('Attach files') ?>
                    </label>
                    <div class="input-box">
                        <?php echo Mage::helper('mstcore/attachment')->getFileInputHtml(Mage::helper('rma/attachment')->getAllowedExtensions()) ?>
                    </div>
                    <?php echo Mage::helper('rma/attachment')->getAttachmentLimits() ?>
                </li>
            </ul>
        </div>

        <?php if ($this->getPolicyIsActive()): ?>
        <div class="fieldset">
            <h2 class="legend" id="policy-title"><?php echo $this->getPolicyTitle() ?></h2>
            <ul class="form-list">
                <li class="wide" id="policy-text">
                    <?php echo $this->getPolicyContent() ?>
                </li>

                <li class="control">
                    <div class="input-box" id="agree-input-box">
                        <input id='agree' type='checkbox' class='required-entry checkbox'> <label for='agree'><?php echo $this->__('I agree') ?></label>
                    </div>
                </li>
            </ul>
        </div>
        <?php endif ?>

        <div class="buttons-set">
            <button type="submit" title="<?php echo $this->getSubmitButtonName() ?>" class="button" id='rma_submit' onclick="return rmaDataFormSubmit(this)"><span><span><?php echo $this->getSubmitButtonName()  ?></span></span></button>
        </div>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var rmaDataForm = new VarienForm("rma-form-validate", true);
        function rmaDataFormSubmit(button){
            if(rmaDataForm.validator &&  rmaDataForm.validator.validate()){
                Form.Element.disable(button);
                rmaDataForm.submit();
            }
            return false;
        }
    //]]>
    </script>

    <style type="text/css">
        #rma_remove_item1 {
            display: none;
        }
    </style>
    <div style="display:none" id="error_message_no_items"><?php echo $this->__('Please, select RMA items which you would like to return.') ?></div>
</div>
