<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php 
		echo $this->headTitle();
	    echo $this->headStyle();
	    ?>
		<meta http-equiv="content-language" content="nl-NL" />
		<meta http-equiv="language" content="nl-NL" />
		<meta name="language" content="nl-NL" />
		<link href="<?=$this->baseUrl()?>/styles/960.css" rel="stylesheet" type="text/css" media="screen" />
		<script type="text/javascript">
			var BASE_URL = "<?= $this->baseUrl()?>";
		</script>
		<?= $this->headScript(); ?>
	</head>

	<body>
		<div class="container_16">
			
			<!-- content -->
			<div id="content">
				<?php echo $this->layout()->content ?>
			</div>
			
		</div>
	</body>
</html>
