<?php $var = $this->getVarModel();?>
<?php $_order = $this->getOrder(); ?>
<?php $shownCredit=false;?>

<?php

$quote = $_order->getQuote();
$storeCredits = Mage::helper('aw_storecredit/totals')->getQuoteStoreCredit($quote->getId());
if (!is_array($storeCredits)) {
    $storeCredits = array();
}

?>

<table
    <?php echo $var->getHtmlAttribute('style', 'order_totals_table_style', "background-color: #ffffff; width: 100% !important; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'order_totals_table_bgcolor', '#ffffff'); ?>
    class="mteditor-bgcolor totals-bg"
    width="100%"  cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td height="15" colspan="3"></td>
    </tr>
    <tr>
        <td width="2%" style="width: 2% !important;"></td>
        <td  align="right">
            <table class="totals-body"  border="0" width="100%" style="width:100%; max-width: 260px"  cellspacing="0" cellpadding="0">
                <tr>
                    <td>

                        <table style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;" border="0" width="100%"  cellspacing="0" cellpadding="0">
                            <tr>
                                <td colspan="5" height="0"></td>
                            </tr>
                            <?php foreach ($this->getTotals() as $_code => $_total): ?>
                                <?php $label = $_total->getLabel(); ?>
                                <?php $code = $_total->getCode(); ?>
                                <?php  if ($_total->getBlockName()): ?>
                                    <?php echo $this->getTotalHtml($_total->getBlockName()); ?>
                                <?php else:?>
                                    <tr>
                                        <td
                                            <?php echo $var->getHtmlAttribute('style', 'order_totals_table_label_style'.$code, 'color: #707582; font-size: 14px; font-weight: bold;'); ?>
                                            <?php if($code != 'discount') { echo $var->getTextEditAttribute('order_totals_table_label_'.$code); }?>
                                            class="mteditor-color total-color">
                                            <?php if($code == 'discount') {
                                                echo $this->escapeHtml($this->__($_total->getLabel()));
                                            } else {
                                                echo $var->getValue('order_totals_table_label_'.$code, $this->escapeHtml($_total->getLabel()), false);
                                            } ?>
                                        </td>
                                        <td width="15" height="25"  style="width: 15px !important; height: 25px"></td>
                                        <td
                                            <?php echo $var->getHtmlAttribute('style', 'order_totals_table_value_style'.$code, 'color: #707582; font-size: 14px; text-align: right;'); ?>
                                            class="mteditor-color total-color"
                                            align="right">
                                            <?php echo $this->formatValue($_total) ?>
                                        </td>
                                    </tr>
                                    <?php
                                        if ($code == 'subtotal')
                                        {
                                            if (count($storeCredits) > 0)
                                            {
                                                foreach ($storeCredits as $storeCredit):
                                                ?>
                                                    <tr>
                                                        <td style="color: #707582; font-size: 14px; font-weight: bold;"><?php echo $this->__('Store Credit'); ?></td>
                                                        <td width="15" height="25"
                                                            style="width: 15px !important; height: 25px"></td>
                                                        <td style="color: #707582; font-size: 14px; text-align: right;">
                                                            -&euro; <?php echo number_format($storeCredit->getStorecreditAmount(), 2, ',', '.'); ?>
                                                        </td>
                                                    </tr>

                                                <?php
                                                endforeach;
                                            }

                                            if ($_order->hasData('points_balance_change') && $_order->getData('points_balance_change') > 0)
                                            {
                                                ?>
                                                <tr>
                                                    <td style="color: #707582; font-size: 14px; font-weight: bold;"><?php echo $this->__('Club Points') ?></td>
                                                    <td width="15" height="25"
                                                        style="width: 15px !important; height: 25px"></td>
                                                    <td style="color: #707582; font-size: 14px; text-align: right;">
                                                        &euro; <?php echo number_format($_order->getData('money_for_points'), 2, ',', '.'); ?></td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                    ?>
                                <?php endif?>
                                <?php if ($_total->getBlockName() == 'tax') $shownCredit=true; ?>
                            <?php endforeach?>
                            <tr >
                                <td colspan="5" height="5"></td>
                            </tr>

                        </table>

                    </td>
                </tr>
            </table>
        </td>
        <td width="2%" style="width: 2% !important;"></td>
    </tr>
    <tr>
        <td height="5" style="height: 5px; font-size: 5px; line-height: 5px">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3" height="1"
            <?php echo $var->getHtmlAttribute('style', 'order_totals_table_bottom_line_style', 'background-color: #e26a0a; font-size:1px; line-height:1px; height:1px;'); ?>
            <?php echo $var->getHtmlAttribute('bgcolor', 'order_totals_table_bottom_line_bg', '#e26a0a'); ?>
            class="mteditor-bgcolor item-line-color ">&nbsp;</td>
    </tr>
</table>

