<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.9.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="aw_points-coupon-box">
    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
        <fieldset class="awpoints__edit-section">
            <legend class="awpoints__edit-section-title"><?php echo $this->__('Coupon Activation') ?></legend>
            <p class="form__field">
                <label class="form__label" for="aw_points-coupon">
                    <?php echo $this->__('Enter coupon code here:') ?>
                </label>
                <input  type="text" id="aw_points-coupon" name="coupon_code" value="" class="form__textfield textfield"/>
            </p>
            <p class="form__field">
                <button type="submit" title="<?php echo $this->__('Activate Coupon') ?>" class="button">
                    <span>
                        <span>
                            <?php echo $this->__('Activate Coupon') ?>
                        </span>
                    </span>
                </button>
            </p>
        </fieldset>
    </form>
</div>