<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.9.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->isEnabled()): ?>
    <div  id="aw_points-history-box" >
        <?php $transactions = $this->getTransactions(); ?>
        <?php if ($transactions->getSize()): ?>
            <h2><?php echo $this->__('Transactions History') ?></h2>
            <table class="data-table" id="points-history-table">
                <tbody>
                    <?php foreach ($transactions as $transaction): ?>
                        <?php $balanceChange = $transaction->getBalanceChange(); ?>
                        <tr>
                            <td style="text-align: right;"><?php echo ($balanceChange > 0 ? "+" . $balanceChange : $balanceChange); ?></td>
                        </tr>
                        <tr class="last">
                            <td>
                                <div><?php echo $this->__($transaction->getActionInstance()->getCommentHtml(AW_Points_Model_Actions_Abstract::FRONTEND)); ?></div>
                                <div>
                                    <?php echo $this->formatDate($transaction->getChangeDate(), 'short', true); ?>
                                    <div class="aw-expiration-in-table">
                                        <?php if ($transaction->getExpirationDate())
                                            echo $this->__('Expires on %s', $this->formatDate($transaction->getExpirationDate(), 'short', true)) ?>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php echo $this->getPagerHtml(); ?>
    <?php endif ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        if (typeof pager != 'undefined') {
            pager.containerId = 'aw_points-history-box';
            pager.tableId = 'points-history-table';
        }
        //]]>
    </script>
<?php endif ?>