<h1><?php echo Mage::helper('sales')->__('Orders and Returns') ?></h1>

<form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
    <fieldset>
        <legend><?php echo Mage::helper('sales')->__('Order Information') ?></legend>
	   <div class="form-group">
			<label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
			<input type="text" class="form-control required-entry" id="oar_order_id" name="oar_order_id" />
	   </div>
		<div class="form-group">
			   <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
	   </div>
	   <div class="form-group">
			<label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
			<input type="text" class="form-control required-entry" id="oar_billing_lastname" name="oar_billing_lastname" />
	   </div>
	   <div class="form-group">
		   <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
		   <select name="oar_type" id="quick_search_type_id" class="form-control select guest-select" title="" onchange="showIdentifyBlock(this.value);">
			   <option value="email">Email Address</option>
			   <option value="zip">ZIP Code</option>
		   </select>
	   </div>
	   <div class="form-group" id="oar-email">
		   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
		   <input type="text" class="form-control validate-email required-entry" id="oar_email" name="oar_email" />
	   </div>
	   <div class="form-group" id="oar-zip" style="display:none;">
			<label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
			<input type="text" class="form-control required-entry" id="oar_zip" name="oar_zip" "/>
	   </div>
    </div>
	<p class="required"><?php echo Mage::helper('sales')->__('* Required Fields') ?></p>
	<button type="submit" title="<?php echo Mage::helper('sales')->__('Continue') ?>" class="btn btn-success"><?php echo Mage::helper('sales')->__('Continue') ?></button>
</form>

<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
