<?php $options = $this->getOptions();?>
<?php if(count($options)):?>
<div class="amshopby-wrapper">
<?php foreach($options as $opt):?>
<div class="amshopby-descr">
<div class="category-head">
<h2><?php echo $opt['title']?></h2>
</div>
<img alt="<?php echo $opt['title']?>" src="<?php echo $opt['image']?>" class="amshopby-logo"/>
<?php echo $opt['descr']?>
</div>
<div style="clear:both"></div>
<?php endforeach?>
</div>
<div style="clear:both"></div>
<?php endif ?>