<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.9.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="awpoints__wrapper">
    <form id="aw_sendinvitation"  action="" method="post">
        <fieldset class="awpoints__send-nvitation-section">
            <legend class="awpoints__send-nvitation-section-title"><?php echo $this->__('Invite your friends by entering their email addresses below') ?></legend>
            <?php if ($maxPerSend = (int) $this->getMaxInvitationsPerSend()): ?>
                <p>
                    <?php echo Mage::helper('points')->__("You shouldn't insert any links in the text - they will be added automatically."); ?>
                </p>
                <p class="form__field form__field--required">
                    <label for="email_1" class="form__label form__label--required">
                        1:
                    </label>
                    <input tabindex="1" name="email[]" id="email_1" title="<?php echo $this->__('Email') ?>" value="" class="form__textfield textfield required-entry validate-email" type="text" />
                </p>
                    <?php for ($_index = 2; $_index <= $maxPerSend; $_index++): ?>
                    <p class="form__field">
                            <label for="email_<?php echo $_index ?>" class="form__label">
                                <?php echo $_index; ?>:
                            </label>
                            <input tabindex="<?php echo $_index ?>" name="email[]" id="email_<?php echo $_index ?>" title="<?php echo $this->__('Email') ?>" value="" class="form__textfield textfield validate-email" type="text" />
                        </p>
                    <?php endfor; ?>
                <p class="form__field">
                    <label for="message" class="form__label"><?php echo $this->__('Message'); ?>: </label>
                    <textarea tabindex="<?php echo $_index + 1 ?>" name="message" id="message" title="<?php echo $this->__('Message') ?>"  class="form__textfield textfield" rows="5" cols="5"></textarea>
                </p>

            <?php endif; ?>
            <p class="form__submit-wrapper">
                <p class="form__required-hint">
                    <?php echo $this->__('Required Fields') ?>
                </p>
                <button type="submit" title="<?php echo $this->__('Send invitation') ?>" class="button">
                    <span>
                        <span>
                            <?php echo $this->__('Send invitation') ?>
                        </span>
                    </span>
                </button>
            </p>
            <p class="awpoints__back-button">
                <a href="<?php echo $this->getBackUrl() ?>" class="button button--invert"><?php echo $this->__('Back to Invitations') ?></a>
            </p>
        </fieldset>
    </form>

    <script type="text/javascript">
        var contactForm = new VarienForm('aw_sendinvitation', true);
    </script>
</div>
