<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">
    <p class="block-subtitle"><?php echo $this->__('Currently Shopping by:') ?></p>
    <ol>
        <?php foreach ($_filters as $_filter): ?>
            <?php $swatch = Mage::getModel('awcolorswatches/swatch');?>
            <?php if (!is_array($_filter->getValue())): $swatch->loadByOptionId($_filter->getValue()); endif;?>
            <?php $isCanShowSwatchImage = $swatch->getId() && $swatch->getImage();?>
            <li>
                <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span>
                <?php if ($isCanShowSwatchImage):?>
                    <?php $_image = AW_Colorswatches_Helper_Image::resizeImage($swatch->getImage(), 16, 16);?>
                    <img src="<?php echo $_image?>" alt="<?php echo $this->stripTags($_filter->getLabel()) ?>" height="16" width="16" title="<?php echo $this->stripTags($_filter->getLabel()) ?>"/>
                <?php endif?>
                <?php if (!$isCanShowSwatchImage || AW_Colorswatches_Helper_Config::isCanShowTextInLayer()):?>
                    <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
                <?php endif;?>

                <?php $clearLinkUrl = $_filter->getClearLinkUrl();
                if ($clearLinkUrl): ?>
                    <a class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>"><?php echo $this->__('Previous') ?></a>
                    <a class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
                <?php else: ?>
                    <a class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"><?php echo $this->__('Remove This Item') ?></a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
