<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()): ?>

    <div id="added-to-cart" class="modal hide" tabindex="-1" role="dialog" aria-hidden="true">
	<!--<div class="block block-cart">-->
	<?php $_cartQty = $this->getSummaryCount() ?>
		<div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<div class="block-title">			
				<strong><span class="icon-shopping-cart"></span><span><?php echo $this->__('Mijn shoppingbag') ?></span></strong>
			</div>
		</div>
	    <div class="modal-body">
		<?php /*if ($_cartQty > 0): ?>
			<div class="summary">
			<?php if ($_cartQty == 1): ?>
					<p><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
				<?php else: ?>
					<p><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
				<?php endif ?>			
			</div>
		<?php endif*/ ?>

		<?php $_items = $this->getRecentItems() ?>
			<?php if (count($_items)): ?>		        
		        <div id="cart-sidebar" class="mini-products-list form-horizontal">
					<?php foreach ($_items as $_item): ?>
						<?php echo $this->getItemHtml($_item) ?>
					<?php endforeach; ?>
		        </div>
		        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
			<?php else: ?>
		        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
			<?php endif ?>
	    </div>
		<?php if ($_cartQty > 0): ?>
			<div class="modal-footer">				
					<?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
					<div class="actions pull-right">
						<?php echo $this->getChildHtml('extra_actions') ?>
						<button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn btn-danger" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
					</div>
					<?php endif ?>
				<?php if ($this->canApplyMsrp()): ?>
					<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
				<?php else: ?>
					<span class="pull-left">
						<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="btn" onclick="history.go(-1)"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
					</span>
				<?php endif; ?>				
			</div>
		<?php endif; ?>
	</div>
<?php endif; ?>
