<script type="text/javascript" charset="utf-8" src="<?php echo $this->getSkinUrl("buckaroo/js/jquery-1.4.4.min.js");?>"></script>
<script>
jQuery.noConflict();

var loader='<div id="buckaroo_loader" style="float: left; display: inline-block;"><img src="<?php echo $this->getSkinUrl('buckaroo/media/ajax-loader.gif');?>" /></div>';
var statuses_url='<?php echo $this->getUrl('admin_buckaroo/adminhtml_statuses');?>';

jQuery(document).ready(function($){

	// Buckaroo tab
    $('#payment_buckaroo_order_state_success').change(function() {
	$('#payment_buckaroo_order_status_success').attr('disabled',true);
	$('#payment_buckaroo_order_status_success').after(loader);

	var state=$('#payment_buckaroo_order_state_success').val();

	$.getJSON(statuses_url,
		           {'state': state},
		           function(data)
		           {
			           var options='';

			           for(var i=0; i<data.length; i++)
			           {
				           options+='<option value="'+data[i].value+'">'+data[i].label+'</option>'+"\n";
			           }

			           $('#payment_buckaroo_order_status_success').empty();
			           $('#payment_buckaroo_order_status_success').html(options); 
		        	   $('#payment_buckaroo_order_status_success').attr('disabled',false);
		        	   $('#buckaroo_loader').remove(); 
			       }
		      );

	});

    $('#payment_buckaroo_order_state_failed').change(function() {
        $('#payment_buckaroo_order_status_failed').attr('disabled',true);
        $('#payment_buckaroo_order_status_failed').after(loader);

        var state=$('#payment_buckaroo_order_state_failed').val();
        
        $.getJSON(statuses_url,
                {'state': state},
                function(data)
                {
                    var options='';

                    for(var i=0; i<data.length; i++)
                    {
                        options+='<option value="'+data[i].value+'">'+data[i].label+'</option>'+"\n";
                    }

                    $('#payment_buckaroo_order_status_failed').empty();
                    $('#payment_buckaroo_order_status_failed').html(options); 
                    $('#payment_buckaroo_order_status_failed').attr('disabled',false);
                    $('#buckaroo_loader').remove(); 
                }
           );
    });	

    
    $('#payment_buckaroo_cancel_on_failed').change(function(){
        var cancel_on_failed=$('#payment_buckaroo_cancel_on_failed').val();

        if(cancel_on_failed==1)
        { 
     	   $('#row_payment_buckaroo_order_state_failed').hide();
     	   $('#row_payment_buckaroo_order_status_failed').hide();
        }
        else
        {
         
       	   $('#row_payment_buckaroo_order_state_failed').show();
     	   $('#row_payment_buckaroo_order_status_failed').show();
        }
    });

    $('#payment_buckaroo_cancel_on_failed').trigger('change');

    // BuckarooCollect tab
    $('#payment_buckaroocollect_order_state_600').change(function() {
    $('#payment_buckaroocollect_order_status_600').attr('disabled',true);
    $('#payment_buckaroocollect_order_status_600').after(loader);

    var state=$('#payment_buckaroocollect_order_state_600').val();

    $.getJSON(statuses_url,
                   {'state': state},
                   function(data)
                   {
                       var options='';

                       for(var i=0; i<data.length; i++)
                       {
                           options+='<option value="'+data[i].value+'">'+data[i].label+'</option>'+"\n";
                       }

                       $('#payment_buckaroocollect_order_status_600').empty();
                       $('#payment_buckaroocollect_order_status_600').html(options); 
                       $('#payment_buckaroocollect_order_status_600').attr('disabled',false);
                       $('#buckaroo_loader').remove(); 
                   }
              );

    });

    $('#payment_buckaroocollect_order_state_601').change(function() {
        $('#payment_buckaroocollect_order_status_601').attr('disabled',true);
        $('#payment_buckaroocollect_order_status_601').after(loader);

        var state=$('#payment_buckaroocollect_order_state_601').val();
        
        $.getJSON(statuses_url,
                {'state': state},
                function(data)
                {
                    var options='';

                    for(var i=0; i<data.length; i++)
                    {
                        options+='<option value="'+data[i].value+'">'+data[i].label+'</option>'+"\n";
                    }

                    $('#payment_buckaroocollect_order_status_601').empty();
                    $('#payment_buckaroocollect_order_status_601').html(options); 
                    $('#payment_buckaroocollect_order_status_601').attr('disabled',false);
                    $('#buckaroo_loader').remove(); 
                }
           );
    }); 

    $('#payment_buckaroocollect_order_state_602_603').change(function() {
        $('#payment_buckaroocollect_order_status_602_603').attr('disabled',true);
        $('#payment_buckaroocollect_order_status_602_603').after(loader);

        var state=$('#payment_buckaroocollect_order_state_602_603').val();
        
        $.getJSON(statuses_url,
                {'state': state},
                function(data)
                {
                    var options='';

                    for(var i=0; i<data.length; i++)
                    {
                        options+='<option value="'+data[i].value+'">'+data[i].label+'</option>'+"\n";
                    }

                    $('#payment_buckaroocollect_order_status_602_603').empty();
                    $('#payment_buckaroocollect_order_status_602_603').html(options); 
                    $('#payment_buckaroocollect_order_status_602_603').attr('disabled',false);
                    $('#buckaroo_loader').remove(); 
                }
           );
    }); 
    
	
});

</script>