<?php
/**
 * Created by PhpStorm.
 * User: mathijs
 * Date: 14-12-17
 * Time: 14:00
 */ 
class Twm_ExtendAwStoreCredit_Model_Storecredit_Observer_Storecredit extends AW_Storecredit_Model_Observer_Storecredit
{
    public function salesOrderCreditmemoRefund(Varien_Event_Observer $observer)
    {
        $creditmemo = $observer->getEvent()->getCreditmemo();

        if (substr($creditmemo->getData('increment_id'), 0, 3) !== 'OFF')
        {
            $request = Mage::app()->getRequest();
            $creditmemoParams = $request->getParam('creditmemo');
            if (!$creditmemoParams
                || !array_key_exists('aw_storecredit_refund_checkbox', $creditmemoParams)
                || !array_key_exists('aw_storecredit_refund_input', $creditmemoParams)
            )
            {
                // do nothing
            }
            else
            {
                $creditmemo->setData('increment_id', 'OFF' . $creditmemo->getData('increment_id'));
                $creditmemo->save();
            }
        }

        $observer->getEvent()->setData('creditmemo', $creditmemo);

        return parent::salesOrderCreditmemoRefund($observer); // TODO: Change the autogenerated stub
    }
}