<?php $_item = $this->getItem() ?>
<?php $_order = $this->getOrder();?>
<?php $var = $this->getVarModel();?>
<?php $helper = Mage::helper('mtemail');?>
<tr
    <?php echo $var->getHtmlAttribute('style', 'order_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'order_item_row_bgcolor', '#ffffff'); ?>
    class="mteditor-bgcolor row-bg-color">
    <td colspan="6" height="5"></td>
</tr>

<tr>
    <td></td>
    <td colspan="3"
        <?php echo $var->getHtmlAttribute('style', 'order_item_name_text', 'color: #707582; font-size: 14px; height:25px!important'); ?>
        height="25" colspan="2" class="mteditor-color table-row-color">
        <b><?php echo $this->escapeHtml($_item->getName()) ?> </b>
    </td>
    <td></td>
</tr>

<tr
    <?php echo $var->getHtmlAttribute('style', 'order_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'order_item_row_bgcolor', '#ffffff'); ?>
    class="mteditor-bgcolor row-bg-color">

    <td></td>
    <td  align="<?php echo $helper->isRTL()?'right':'left';?>" height="35">
        <table cellpadding="0" cellspacing="0" border="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; ">

            <?php if ($this->showSKU()): ?>
                <tr

                    <?php echo $var->getHtmlAttribute('style', 'order_item_options', 'color: #707582; font-size: 15px; line-height: 20px'); ?>
                    class="mteditor-color table-row-color">

                    <td <?php echo $var->getTextEditAttribute('order_item_options_sku_text_2');?>
                        <?php echo $var->getHtmlAttribute('style', 'order_item_options_sku_v', 'font-size: 14px; font-weight: bold'); ?> height="25" >
                        <?php echo $var->getValue('order_item_options_sku_text_2', "Item ID");?>&nbsp;&nbsp;
                    </td>
                    <td style="font-size: 14px;">
                        <?php echo $this->escapeHtml($this->getSku($_item)) ?>
                    </td>
                </tr>
            <?php endif; ?>

            <?php if ($this->getItemOptions()): ?>
                <?php foreach ($this->getItemOptions() as $option): ?>
                    <tr
                        <?php echo $var->getHtmlAttribute('style', 'order_item_options', 'color: #707582; font-size: 15px; line-height: 20px'); ?>
                        class="mteditor-color table-row-color">
                        <td height="25" style="font-size: 14px; font-weight: bold"><?php echo $option['label'] ?>&nbsp;&nbsp;</td>
                        <td style="font-size: 14px; "><?php echo nl2br($option['value']) ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="2" height="3"></td>
                </tr>

            <?php endif; ?>
        </table>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
    </td>

    <td
        <?php echo $var->getHtmlAttribute('style', 'order_item_name_text_qty', 'color: #707582; font-size: 14px; height:25px!important'); ?>
        class="mteditor-color table-row-color"
        align="center" height="35" valign="top">
        <?php echo $_item->getQtyOrdered()*1 ?>
    </td>
    <td
        <?php echo $var->getHtmlAttribute('style', 'order_item_name_text_subtotal', 'color: #707582; font-size: 14px; height:25px!important'); ?>
        class="mteditor-color table-row-color"
        align="<?php echo $helper->isRTL()?'left':'right';?>"  height="35"  valign="top">
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span ><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span ><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <td></td>
</tr>
<tr
    <?php echo $var->getHtmlAttribute('style', 'order_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'order_item_row_bgcolor', '#ffffff'); ?>
    class="mteditor-bgcolor row-bg-color">
    <td colspan="6" height="5"></td>
</tr>
