<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>
<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <?php $swatch = Mage::getModel('awcolorswatches/swatch')->loadByOptionId($_item->getValue());?>
            <?php $isCanShowSwatchImage = $swatch->getId() && $swatch->getImage();?>
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" <?php if($isCanShowSwatchImage):?>class="aw-colorswatches-layer-filter"<?php endif;?>>
            <?php else:?>
                <span>
            <?php endif;?>
                <?php if($isCanShowSwatchImage):?>
                    <?php $_image = AW_Colorswatches_Helper_Image::resizeImage($swatch->getImage(), 16, 16);?>
                    <img src="<?php echo $_image?>" height="16" width="16" alt="<?php echo $_item->getLabel() ?>" title="<?php echo $_item->getLabel() ?>"/>
                <?php endif;?>
                <?php if (!$isCanShowSwatchImage || AW_Colorswatches_Helper_Config::isCanShowTextInLayer()):?>
                    <?php echo $_item->getLabel() ?>
                <?php endif;?>
                <?php if (!method_exists($this,'shouldDisplayProductCount') || $this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            <?php if ($_item->getCount() > 0): ?></a><?php else:?></span><?php endif;?>
        </li>
    <?php endforeach ?>
</ol>