<?php
/* @var $this Mirasvit_Rma_Block_Rma_List_List */
/* @var $rma Mirasvit_Rma_Model_Rma */
$collection = $this->getRmaCollection();
?>
<?php if ($collection->count()): ?>
    <?php echo $this->getChildHtml('rma.toolbar')?>
    <table class="data-table" id="rma-table">
        <thead>
        <tr class="first last">
            <th><?php echo $this->__('RMA') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Order') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($collection as $rma): ?>
                <tr>
                    <td><?php echo $rma->getIncrementId() ?>
                        <?php if ($rma->getLastComment() && !$rma->getLastComment()->getIsRead()): ?><span class="unread"></span><?php endif;?>
                    </td>
                    <td><?php echo Mage::helper('core')->formatDate($rma->getCreatedAt(), 'medium') ?></td>
                    <td>
                        <?php foreach ($rma->getOrders() as $order): ?>
                            <?php if ($order->getId()): ?>
                                <div>
                                    <?php echo Mage::helper('rma')->getOrderLabel($order, $this->getOrderUrl($order->getId()))?>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php foreach ($rma->getOfflineOrders() as $order): ?>
                                <div>
                                    <?php echo $order->getReceiptNumber()?>
                                </div>
                        <?php endforeach; ?>


                    </td>
                    <td><?php echo Mage::helper('rma/locale')->getLocaleValue($rma->getStatus(), 'name') ?></td>
                    <td><a href="<?php echo $rma->getUrl()?>"><?php echo $this->__('View Return') ?></a></td>
                </tr>
        <?php endforeach?>
        </tbody>
    </table>
    <?php echo $this->getChildHtml('rma.toolbar')?>
    <script type="text/javascript">decorateTable('rma-table')</script>
<?php else: ?>
    <p><?php echo $this->__('There are no Returns') ?></p>
<?php endif ?>
