<?php if ($this->getApi()->getClient()->isAccessTokenExpired()):?>
	<a href="<?php echo $this->getApi()->getClient()->createAuthUrl()?>">Login to Google</a>
<?php else: ?>
	<div>
		<div style="margin:0px 0px 10px 0px"><strong>CHOOSE ITEMS TO CREATE</strong></div>
		<div style="margin:0px 0px 10px 0px">The following items will be created next time you click "Save config" button.</div>
	</div>
	<div>
		<div><label for="ec_api_variables"><input type="checkbox" name="args[]" value="ec_api_variables" id="ec_api_variables" /> Create variables</label></div>
		<div><label for="ec_api_triggers"><input type="checkbox" name="args[]" value="ec_api_triggers" id="ec_api_triggers" /> Create triggers</label></div>
		<div><label for="ec_api_tags"><input type="checkbox" name="args[]" value="ec_api_tags" id="ec_api_tags" /> Create tags</label></div>
	</div>
	<div style="margin:10px 0px 10px 0px">
		Make sure Container and Account ID and your account is authorised with corresponding permissions.
	</div>
<?php endif ?>