<?php
class Total_Buckaroo_Model_PaymentMethod extends Mage_Payment_Model_Method_Abstract
{
    /**
    * unique internal payment method identifier
    * 
    * @var string [a-z0-9_]
    */
    protected $_code = 'buckaroo';

    protected $_formBlockType = 'buckaroo/checkout_form';
    /**
     * Here are examples of flags that will determine functionality availability
     * of this module to be used by frontend and backend.
     * 
     * @see all flags and their defaults in Mage_Payment_Model_Method_Abstract
     *
     * It is possible to have a custom dynamic logic by overloading
     * public function can* for each flag respectively
     */
     
    /**
     * Availability options
     */
    protected $_isGateway               = true;
    protected $_canAuthorize            = true;
    protected $_canCapture              = true;
    protected $_canCapturePartial       = true;
    protected $_canRefund               = true;
    protected $_canVoid                 = true;
    protected $_canUseInternal          = true;
    protected $_canUseCheckout          = true;
    protected $_canUseForMultishipping  = true;
    protected $_canSaveCc = false;
    
    const BUCKAROO_SUCCESS='SUCCESS';
    const BUCKAROO_FAILED='FAILED';
    const BUCKAROO_NEUTRAL='NEUTRAL';

    public static function saveInvoice(Mage_Sales_Model_Order $order, $amount){
        
        if ($order->canInvoice()) {
            // if full amount is paid create invoice, if amount different register payment
            $payment = $order->getPayment()->registerCaptureNotification($amount);
            $order->save();
            return true;
        }
        
        return false;
    }
    
    public static function saveQuoteId()
    {
        // Save quote_id
        // Mage::getSingleton('checkout/session')->getQuote()->setIsActive(false)->save();
        Mage::getSingleton('checkout/session')->setBuckarooQuoteId(Mage::getSingleton('checkout/session')->getQuoteId());
        
        // Mage::getSingleton('checkout/session')->clear();
    }
    
    public function getOrderPlaceRedirectUrl()
    {
        self::saveQuoteId();
                
    	return Mage::getUrl('buckaroo/checkout/redirect', array('_secure' => true));
    }
    
    static public function getStateAndStatusByCode($code)
    {
        switch($code)
        {
            case self::BUCKAROO_SUCCESS: $return=array(Mage::getStoreConfig('payment/buckaroo/order_state_success', Mage::app()->getStore()->getStoreId()), Mage::getStoreConfig('payment/buckaroo/order_status_success', Mage::app()->getStore()->getStoreId()));
                                         break;
                                         
            case self::BUCKAROO_FAILED:  $return=array(Mage::getStoreConfig('payment/buckaroo/order_state_failed', Mage::app()->getStore()->getStoreId()), Mage::getStoreConfig('payment/buckaroo/order_status_failed', Mage::app()->getStore()->getStoreId()));
                                         break;
                                         
            case self::BUCKAROO_NEUTRAL: $return=array(null, null);
                                         break;                                                                                 
        }    
        
        return $return;
    }
    
    static public function process_responsecodes($responsecode, $order=null)
	{
		
// Buckaroo messages
// 
// 1.
// if you need to set order status for the payment method - code combination
// you should put a new answer array for the specific payment method
// * is default payment method 
// check example for the '300'
//
// 2.
// You can translate any of Buckaroo answer descriptions, you need just edit
// /app/locale/nl_NL/Total_Buckaroo.csv file (or create/update translation file under another locale)
//

$responsecode_array = array(0	 => array( '*'=>array(	"omschrijving" => "De credit card transactie is pending.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),
							1	 => array( '*'=>array(	"omschrijving" => "De credit card transactie is pending. De MPI-status van de klant wordt gecheckt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),
							70	 => array( '*'=>array(	"omschrijving" => "De refund is nog niet verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),
							71	 => array( '*'=>array(	"omschrijving" => "De refund is succesvol verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),
							72	 => array( '*'=>array(	"omschrijving" => "Er is een fout opgetreden bij het refunden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							73	 => array( '*'=>array(	"omschrijving" => "De refund is geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							100	 => array( '*'=>array(	"omschrijving" => "De transactie is door de credit-maatschappij goedgekeurd.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "creditcard")),
							101	 => array( '*'=>array(	"omschrijving" => "De transactie is door de credit-maatschappij afgekeurd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							102	 => array( '*'=>array(	"omschrijving" => "De transactie is mislukt. Er is een fout opgetreden in de verwerking bij de creditmaatschappij.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							103	 => array( '*'=>array(	"omschrijving" => "Deze creditcardtransactie is niet binnen de maximale,  toegestane tijd uitgevoerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							104	 => array( '*'=>array(	"omschrijving" => "De kaart is verlopen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							120	 => array( '*'=>array(	"omschrijving" => "Deze PayPal transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							121	 => array( '*'=>array(	"omschrijving" => "Transactiestatus: autorisatie geslaagd.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "paypal")),
							122	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is door de consument geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							123	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is niet binnen de maximale, toegestane tijd uitgevoerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							124	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is om onbekende reden bij PayPal mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							125	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is niet geaccepteerd.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							126	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is in afwachting.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							135	 => array( '*'=>array(	"omschrijving" => "Deze PayPal-transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							136	 => array( '*'=>array(	"omschrijving" => "Om technische reden kon de status van deze transactie nog niet bij PayPal worden achterhaald. De transactie is mogelijk nog niet afgerond",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							137	 => array( '*'=>array(	"omschrijving" => "De afschrijvingscode is ongeldig.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							138	 => array( '*'=>array(	"omschrijving" => "Er is een systeemfout opgetreden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							139	 => array( '*'=>array(	"omschrijving" => "Het PayPal transactie-ID is ongeldig of niet beschikbaar.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							140	 => array( '*'=>array(	"omschrijving" => "Er kon geen transactie worden gevonden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							150	 => array( '*'=>array(	"omschrijving" => "Deze Paysafecard-transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							151	 => array( '*'=>array(	"omschrijving" => "Transactiestatus: authorisatie geslaagd.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "paypal")),
							152	 => array( '*'=>array(	"omschrijving" => "Deze Paysafecard-transactie is door de consument geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							153	 => array( '*'=>array(	"omschrijving" => "Deze Paysafecard-transactie is niet binnen de maximale, toegestane tijd uitgevoerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							155	 => array( '*'=>array(	"omschrijving" => "Deze Paysafecard-transactie is niet geaccepteerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							156  => array( '*'=>array(	"omschrijving" => "Deze Paysafecard-transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							157	 => array( '*'=>array(	"omschrijving" => "Om technische reden kon de status van deze transactie nog niet bij Paysafecard worden achterhaald. De transactie is mogelijk nog niet afgerond.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							158	 => array( '*'=>array(	"omschrijving" => "Er is een systeemfout opgetreden bij Paysafecard. Onze excuses voor het ongemak.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							159	 => array( '*'=>array(	"omschrijving" => "Het Paysafecard transactie-id is ongeldig of niet beschikbaar.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "paypal")),
							170	 => array( '*'=>array(	"omschrijving" => "Deze Cash-Ticket transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypal")),
							171	 => array( '*'=>array(	"omschrijving" => "Transactiestatus: authorisatie geslaagd",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "creditcard")),
							172	 => array( '*'=>array(	"omschrijving" => "Deze Cash-Ticket transactie is door de consument geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							173	 => array( '*'=>array(	"omschrijving" => "Deze Cash-Ticket transactie is niet binnen de maximale, toegestane tijd uitgevoerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							175	 => array( '*'=>array(	"omschrijving" => "Deze Cash-Ticket transactie is niet geaccepteerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),				
							176  => array( '*'=>array(	"omschrijving" => "Deze Cash-Ticket transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),				
							177  => array( '*'=>array(	"omschrijving" => "Om technische reden kon de status van deze transactie nog niet bij Cash-Ticket worden achterhaald. De transactie is mogelijk nog niet afgerond.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),				
							178  => array( '*'=>array(	"omschrijving" => "Er is een systeemfout opgetreden bij Cash-Ticket. Onze excuses voor het ongemak.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							179  => array( '*'=>array(	"omschrijving" => "Het Cash-Ticket transactie-id is ongeldig of niet beschikbaar.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")), 
							201	 => array( '*'=>array(	"omschrijving" => "Er is timeout opgetreden bij het verwerken van de transactie.Gebruik de TransactionKey om de verwerkingsstatus nogmaals te controleren.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "creditcard")),
							203	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd. Het creditcardnummer is geblokkeerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							204	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd. Het ip-adres is geblokkeerd",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							205	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd. Het land van uitgifte van deze creditcard is geblokkeerd",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							206	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd. De faktuur [waarde] wordt momenteel of is reeds betaald.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							207	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd. Het maximaal aantal betaalpogingen voor faktuur [waarde] is overschreden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							242  => array( '*'=>array(  "omschrijving" => "Provisie BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							243  => array( '*'=>array(  "omschrijving" => "Provisie incassobureau BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							244  => array( '*'=>array(  "omschrijving" => "Provisie Buckaroo BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							245  => array( '*'=>array(  "omschrijving" => "Toetskosten incassobureau BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							246  => array( '*'=>array(  "omschrijving" => "Btw incassobureau BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							247  => array( '*'=>array(  "omschrijving" => "Btw buckaroo BetaalGarant succesvol verwerkt.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),				
							252	 => array( '*'=>array(	"omschrijving" => "Kredietwaardigheidcontrole resultaat negatief.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "garant")),
							254  => array( '*'=>array(  "omschrijving" => "Payment Guarantee request successfully processed.",
											"code" => self::BUCKAROO_SUCCESS,
											"type" => "garant")),
							260	 => array( '*'=>array(	"omschrijving" => "Kredietwaardigheidcontrole abonnement niet actief.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "garant")),
							261	 => array( '*'=>array(	"omschrijving" => "Technische fout opgetreden tijdens kredietwaardigheidcontrole.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "garant")),
							262	 => array( '*'=>array(	"omschrijving" => "Verplichte velden voor kredietwaardigheidcontrole ontbreken of zijn onjuist",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "garant")),																																				
							300	 => array( '*'=>array("omschrijving" => "Betaling voor deze overschrijving wordt nog verwacht.",
													 "code" => self::BUCKAROO_NEUTRAL,
													 "type" => "transfer"),
										   'buckarootransfergarant'=>array("omschrijving" => "Uw bestelling is geaccepteerd.",
											  		 					   "code" => self::BUCKAROO_SUCCESS,
													 					   "type" => "transfer")),
							301	 => array( '*'=>array(	"omschrijving" => "De overschrijving is ontvangen.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "transfer")),
							302	 => array( '*'=>array(	"omschrijving" => "De transactie is geweigerd of afgewezen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							303	 => array( '*'=>array(	"omschrijving" => "De uiterste betaaldatum voor deze overschrijving is verstreken.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							304	 => array( '*'=>array(	"omschrijving" => "De datum voor ingebrekestelling is verstreken.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "transfer")),
							305	 => array( '*'=>array(	"omschrijving" => "Het ontvangen bedrag voor de overschrijving is lager dan het bedrag van de transactie.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "transfer")),
							306	 => array( '*'=>array(	"omschrijving" => "Het ontvangen bedrag voor de overschrijving is groter dan het bedrag van de transactie.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "transfer")),
							309	 => array( '*'=>array(	"omschrijving" => "De overschrijving is geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							345  => array( '*'=>array(	"omschrijving" => "Oorspronkelijk transactie-bedrag gedeeld.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							371	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is verwerkt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "creditcard")),
							372	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is verwerkt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							373	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is verwerkt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							381	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							382	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							383	 => array( '*'=>array(	"omschrijving" => "De refund voor deze overschrijving is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "transfer")),
							390	 => array( '*'=>array(	"omschrijving" => "De transactie is buiten Buckaroo om met de klant afgehandeld.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "transfer")),
							392	 => array( '*'=>array(	"omschrijving" => "Anders betaald.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "transfer")),
							400	 => array( '*'=>array(	"omschrijving" => "De kadokaart-transactie is nog in behandeling",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "giftcard")),
							401	 => array( '*'=>array(	"omschrijving" => "De betaling middels kado-kaart is geslaagd.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							402	 => array( '*'=>array(	"omschrijving" => "Betaling middels de kadokaart is afgewezen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							409	 => array( '*'=>array(	"omschrijving" => "Betaling middels de kadokaart is geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							403	 => array( '*'=>array(	"omschrijving" => "Deze Giftcard transactie is niet binnen de maximale, toegestane tijd uitgevoerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							404	 => array( '*'=>array(	"omschrijving" => "Deze Giftcard transactie is om onbekende reden bij de kaartuitgever mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							409	 => array( '*'=>array(	"omschrijving" => "Betaling middels de kadokaart is geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							410	 => array( '*'=>array(	"omschrijving" => "De Merchant Account Code is ongeldig",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							411	 => array( '*'=>array(	"omschrijving" => "De betaling middels kad-kaart is voorlopig geaccepteerd.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							414	 => array( '*'=>array(	"omschrijving" => "Er is een systeem-fout opgetreden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							421	 => array( '*'=>array(	"omschrijving" => "Er is een onbekende Issuer voor de kado-kaart opgegeven.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							422	 => array( '*'=>array(	"omschrijving" => "Er is een fout opgetreden bij de Issuer. De betaling is mislukt. [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							425	 => array( '*'=>array(	"omschrijving" => "Niet genoeg saldo om deze transactie uit te voeren.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							461  => array( '*'=>array(	"omschrijving" => "Transactie voltooid.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							462  => array( '*'=>array(	"omschrijving" => "Transactie voltooid.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							463  => array( '*'=>array(	"omschrijving" => "Transactie voltooid.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							464  => array( '*'=>array(	"omschrijving" => "Transactie voltooid.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							468  => array( '*'=>array(	"omschrijving" => "Originele factuur voor deze vordering niet gevonden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							471	 => array( '*'=>array(	"omschrijving" => "De refund voor deze giftcardbetaling is verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "giftcard")),
							472	 => array( '*'=>array(	"omschrijving" => "De refund voor deze giftcardbetaling is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "giftcard")),
							500	 => array( '*'=>array(	"omschrijving" => "Paypermail: transactie pending",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							541	 => array( '*'=>array(	"omschrijving" => "Transactiekosten zijn verrekend met saldo.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							550	 => array( '*'=>array(	"omschrijving" => "De uitbetaling is nog niet verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							551	 => array( '*'=>array(	"omschrijving" => "De uitbetaling is succesvol verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "paypermail")),
							552	 => array( '*'=>array(	"omschrijving" => "Transactiekosten zijn verrekend met saldo.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							553  => array( '*'=>array(	"omschrijving" => "Transactiekosten zijn verrekend met saldo.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							560	 => array( '*'=>array(	"omschrijving" => "Correctiebetaling uitgevoerd door Buckaroo.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							581	 => array( '*'=>array(	"omschrijving" => "Overschrijving van of naar ander Buck-account.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "paypermail")),
							600	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is nog niet verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "collect")),
							601	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is met succes verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "collect")),
							602	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is door de bank afgewezen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							605	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is gestorneerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							609	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is geannuleerd voordat incasso plaatsvond.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							610	 => array( '*'=>array(	"omschrijving" => "Eenmalige machtiging is door de bank afgewezen. Rekening ongeldig.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							612	 => array( '*'=>array(	"omschrijving" => "Terugboeking wegens Melding Onterechte Incasso",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							671	 => array( '*'=>array(	"omschrijving" => "De refund voor deze machtiging is verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "collect")),
							672	 => array( '*'=>array(	"omschrijving" => "De refund voor deze machtiging is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "collect")),
							700	 => array( '*'=>array(	"omschrijving" => "De betaalopdracht is geaccepteerd en wordt in behandeling genomen.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "batch")),
							701	 => array( '*'=>array(	"omschrijving" => "De betaalopdracht is verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "batch")),
							702	 => array( '*'=>array(	"omschrijving" => "De betaalopdracht is door de bank teruggestort wegens incorrecte rekeninggegevens.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							703  => array( '*'=>array(	"omschrijving" => "De betaalopdracht is afgewezen door Buckaroo.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							704  => array( '*'=>array(	"omschrijving" => "Betaalopdracht geannuleerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							705	 => array( '*'=>array(	"omschrijving" => "De batch kon niet worden ingepland. Error: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							710	 => array( '*'=>array(	"omschrijving" => "Betaalopdracht nog niet geverifieerd.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "batch")),
							711	 => array( '*'=>array(	"omschrijving" => "De batch kon niet gevonden worden: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							712	 => array( '*'=>array(	"omschrijving" => "De batch is reeds verwerkt: [waarde].",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "batch")),
							720	 => array( '*'=>array(	"omschrijving" => "Er is voor deze batch-transactie geen klant-id opgegeven.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							721	 => array( '*'=>array(	"omschrijving" => "Het opgegeven klant-id kon niet worden gevonden: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "batch")),
							800	 => array( '*'=>array(	"omschrijving" => "Deze iDeal-transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "ideal")),
							801	 => array( '*'=>array(	"omschrijving" => "Deze iDeal-transactie is met succes verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "ideal")),
							802	 => array( '*'=>array(	"omschrijving" => "Deze iDeal-transactie is door de consument geannuleerd. Trx: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							803	 => array( '*'=>array(	"omschrijving" => "Deze iDeal-transactie is niet binnen de maximale toegestane tijd uitgevoerd. Trx: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							804	 => array( '*'=>array(	"omschrijving" => "Deze iDeal-transactie is om onbekende reden bij de bank mislukt. Trx: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							810	 => array( '*'=>array(	"omschrijving" => "Issuer (bank) is onbekend: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							811	 => array( '*'=>array(	"omschrijving" => "Om technische reden kon de status van deze transactie nog niet bij de bank worden achterhaald. De transactie is nog niet afgerond.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "ideal")),
							812	 => array( '*'=>array(	"omschrijving" => "De entrance-code [waarde] is ongeldig.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							813	 => array( '*'=>array(	"omschrijving" => "Acquirer-code is onbekend: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							814	 => array( '*'=>array(	"omschrijving" => "Er is een systeemfout opgetreden. We zullen deze zo snel mogelijk verhelpen. De status zal daarna worden herzien.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "ideal")),
							815	 => array( '*'=>array(	"omschrijving" => "Op dit moment is de betaalmethode iDEAL niet beschikbaar wegens een storing bij de bank.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							816	 => array( '*'=>array(	"omschrijving" => "Er kon geen transactie worden gevonden. Criteria: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							820	 => array( '*'=>array(	"omschrijving" => "Deze Giropay-transactie is nog niet volledig verwerkt.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "ideal")),
							821	 => array( '*'=>array(	"omschrijving" => "Deze Giropay-transactie is met succes verwerkt.",
											"code"		=> self::BUCKAROO_SUCCESS,
											"type"		=> "ideal")),
							822	 => array( '*'=>array(	"omschrijving" => "Deze Giropay-transactie is door de consument geannuleerd. Trx: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							823	 => array( '*'=>array(	"omschrijving" => "Deze Giropay-transactie is niet binnen de maximale toegestane tijd uitgevoerd. Trx: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							824	 => array( '*'=>array(	"omschrijving" => "Deze Giropay-transactie is door de bank afgewezen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							830	 => array( '*'=>array(	"omschrijving" => "Issuer (bankleitzahl) is onbekend: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							831	 => array( '*'=>array(	"omschrijving" => "Om technische reden kon de status van deze transactie nog niet bij de bank worden achterhaald. De transactie is nog niet afgerond.",
											"code"		=> self::BUCKAROO_NEUTRAL,
											"type"		=> "ideal")),
							833	 => array( '*'=>array(	"omschrijving" => "De entrance-code [waarde] is ongeldig.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							834	 => array( '*'=>array(	"omschrijving" => "Er is een systeemfout opgetreden. We zullen deze zo snel mogelijk verhelpen. De status zal daarna worden herzien.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							835	 => array( '*'=>array(	"omschrijving" => "Het Giropay transactie-id is ongeldig of niet beschikbaar.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							836	 => array( '*'=>array(	"omschrijving" => "Er kon geen transactie worden gevonden. Criteria: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							871	 => array( '*'=>array(	"omschrijving" => "De refund voor deze iDeal-cardbetaling is verwerkt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							872	 => array( '*'=>array(	"omschrijving" => "De refund voor deze iDeal-cardbetaling is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							873	 => array( '*'=>array(	"omschrijving" => "De refund voor deze GiroPay-cardbetaling is verwerkt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							874	 => array( '*'=>array(	"omschrijving" => "De refund voor deze GiroPay-betaling is mislukt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "ideal")),
							900	 => array( '*'=>array(	"omschrijving" => "Geen XML-bericht ontvangen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							901	 => array( '*'=>array(	"omschrijving" => "Ongeldig XML-bericht.  [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							910	 => array( '*'=>array(	"omschrijving" => "0 EUR transactie, Customergegevens opgeslagen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							931	 => array( '*'=>array(	"omschrijving" => "[nodetype] [element] ontbreekt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							932	 => array( '*'=>array(	"omschrijving" => "Teveel elementen type [element] (max. 1).",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							933	 => array( '*'=>array(	"omschrijving" => "Waarde [nodetype] [element] ontbreekt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							934	 => array( '*'=>array(	"omschrijving" => "Waarde [nodetype] [element] (occurance [occurance]) ontbreekt.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							935	 => array( '*'=>array(	"omschrijving" => "Waarde attribuut [attribuut] ontbreekt in element [element].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							940	 => array( '*'=>array(	"omschrijving" => "Ongeldig request: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							941	 => array( '*'=>array(	"omschrijving" => "Waarde veld [veld] ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							942	 => array( '*'=>array(	"omschrijving" => "Waarde attribuut [veld] ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							943	 => array( '*'=>array(	"omschrijving" => "Creditcard-type onbekend: [waarde]. (mastercard of visa)",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							944	 => array( '*'=>array(	"omschrijving" => "Kaartnummer ongeldig (Luhn-check): [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							945	 => array( '*'=>array(	"omschrijving" => "Valuta onbekend ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							946	 => array( '*'=>array(	"omschrijving" => "Bedrag is geen numerieke waarde: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							947	 => array( '*'=>array(	"omschrijving" => "Bedrag ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							948	 => array( '*'=>array(	"omschrijving" => "CVC-code ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							949	 => array( '*'=>array(	"omschrijving" => "Maand geldigheidsduur creditcard ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							950	 => array( '*'=>array(	"omschrijving" => "Jaar geldigheidsduur creditcard ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							951	 => array( '*'=>array(	"omschrijving" => "Taal onbekend of niet ondersteund: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							952	 => array( '*'=>array(	"omschrijving" => "Het factuurnummer ontbreekt. Dit veld is verplicht.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							953	 => array( '*'=>array(	"omschrijving" => "Geblokkeerd door velocitycheck",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							954	 => array( '*'=>array(	"omschrijving" => "Het transactie-ID [waarde] is al in gebruik.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							955	 => array( '*'=>array(	"omschrijving" => "Authenticatie voor deze creditcard betaling is afgewezen",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							956	 => array( '*'=>array(	"omschrijving" => "De enrolled status van de creditcard kon niet achterhaald worden.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							960	 => array( '*'=>array(	"omschrijving" => "Klantnummer ongeldig: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							961	 => array( '*'=>array(	"omschrijving" => "Creditcard-type niet geactiveerd: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							962	 => array( '*'=>array(	"omschrijving" => "Gekozen valuta ongeldig voor Merchant: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							963	 => array( '*'=>array(	"omschrijving" => "Het transactie-id is ongeldig: [waarde]",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							964	 => array( '*'=>array(	"omschrijving" => "Er zijn geen betaalmethoden geactiveerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							971  => array( '*'=>array(	"omschrijving" => "Er is geen naam opgegeven.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							972  => array( '*'=>array(	"omschrijving" => "Er is geen adres opgegeven.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							973  => array( '*'=>array(	"omschrijving" => "Er is geen postcode ingevuld.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							974  => array( '*'=>array(	"omschrijving" => "Er is geen plaats ingevuld.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							975  => array( '*'=>array(	"omschrijving" => "Er is geen land ingevuld.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							976  => array( '*'=>array(	"omschrijving" => "Er is geen geslacht ingevuld.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							977  => array( '*'=>array(	"omschrijving" => "Mailadres ongeldig.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							978	 => array( '*'=>array(	"omschrijving" => "De XML koppeling voor creditcards is nog niet geactiveerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							980	 => array( '*'=>array(	"omschrijving" => "De betaalmethode [waarde] is niet geactiveerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							981	 => array( '*'=>array(	"omschrijving" => "De datum van het abonnement is geen geldige datum.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							982  => array( '*'=>array(	"omschrijving" => "Het abonnement is nog niet ingegaan.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							983	 => array( '*'=>array(	"omschrijving" => "Het abonnement is verlopen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							990	 => array( '*'=>array(	"omschrijving" => "De digitale handtekening is incorrect: [waarde].",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							991	 => array( '*'=>array(	"omschrijving" => "Er is een fout opgetreden bij het verwerken van de transactie. De Merchant Account Code kon niet worden gelocaliseerd.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							992	 => array( '*'=>array(	"omschrijving" => "Er is fout opgetreden bij het verwerken van de response. We zullen de storing zo snel mogelijk verhelpen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							993	 => array( '*'=>array(	"omschrijving" => "Er is een fout opgetreden bij het verwerken van de transactie. We zullen de storing zo snel mogelijk verhelpen.",
											"code"		=> self::BUCKAROO_FAILED,
											"type"		=> "xml")),
							999	 => array( '*'=>array(	"omschrijving" => "Er is een fout opgetreden waarvan de oorzaak vooralsnog onbekend is. We zullen de storing zo snel mogelijk verhelpen.",
											"code"		=> self::BUCKAROO_FAILED))
);
		
		// messages
		if($order==null)
		{
			if(isset($responsecode_array[$responsecode]) && is_array($responsecode_array[$responsecode]['*']))
			{
				return $responsecode_array[$responsecode]['*'];
			}
		}
		else
		{
			$method=$order->getPayment()->getMethod();

			if(isset($responsecode_array[$responsecode]))
			{
				if(isset($responsecode_array[$responsecode][$method]) && is_array($responsecode_array[$responsecode][$method]))
				{
					return $responsecode_array[$responsecode][$method];
				}
				else if(isset($responsecode_array[$responsecode]['*']) && is_array($responsecode_array[$responsecode]['*']))
				{
					return $responsecode_array[$responsecode]['*'];
				}
			}
		}
	
		//return error
		$return_array["code"] = self::BUCKAROO_FAILED;
		$return_array["omschrijving"] = "Unexpected response code";
	
		return $return_array;
	}

}