<?php if(Mage::app()->getStore()->getCode() == 'jma_nl') { ?>
	<?php $product = Mage::registry('current_product'); ?>
	<script type="text/javascript">
		var _ac = {};

		<?php if (!is_null($product)) : ?>
		_ac.value = '<?php echo $product->getFinalPrice() ?>';
		_ac.product = '<?php echo $product->getSku() ?>';
		<?php endif ?>

		(function(d, t) {
			var a = d.createElement(t), s = d.getElementsByTagName(t)[0];
			a.async = a.src = '//pixel.adcrowd.com/smartpixel/c6036a69be21cb660499b75718a3ef24.js';
			s.parentNode.insertBefore(a, s);
		}(document, 'script'));
	</script>
<?php } ?>