<div class="grid_6 alpha">
	<div class="imagelink large big color corners" style="background-image: url(<?=$this->getSkinUrl('images/newImage.jpg');?>);">
		<div class="corner clt">&nbsp;</div>
		<div class="corner crt">&nbsp;</div>
		<div class="corner crb">&nbsp;</div>
		<div class="corner clb">&nbsp;</div>
		<span><?=$this->getChildHtml('cms_new');?></span>
	</div>
	<p>Deze webshop is een initiatief van Oxener Schoenen.</p>
</div>
