<div class="imagelink small tiny" style="background-image: url(<?=$this->getSkinUrl('images/profitImage.jpg');?>);">
	<div class="opacity">&nbsp;</div>
	<div class="corner clt">&nbsp;</div>
	<div class="corner crt">&nbsp;</div>
	<div class="corner crb">&nbsp;</div>
	<div class="corner clb">&nbsp;</div>
	<h2>Voordelen webshop</h2>
	<div id="profit">
		<?=$this->getChildHtml('cms_profit');?>
	</div>
</div>