<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="<?=$this->baseUrl()?>/admin/styles/admin.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?=$this->baseUrl()?>/admin/ext/resources/css/ext-all.css" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="<?=$this->baseUrl()?>/admin/ext/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?=$this->baseUrl()?>/admin/ext/ext-all-debug.js"></script>
        <script type="text/javascript" src="<?=$this->baseUrl()?>/admin/ext/api"></script>
        <title>Admin</title>
        <meta http-equiv="content-language" content="nl-NL" />
        <meta http-equiv="language" content="nl-NL" />
        <meta name="language" content="nl-NL" />
        <?php
        echo $this->headScript()->appendScript ( "var __BASE_URL = '{$this->baseUrl()}';\n", 'text/javascript' );
        echo $this->headStyle();
        ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
    </body>
</html>
