<script type="text/javascript">

	var ecomm = 
	{
			i: [], /* ecomm_prodid[] array */
			v: [], /* ecomm_pvalue[] array */
			p: []  /* ecomm_pname[]  array */
	}

	<?php foreach ($this->getItems() as $item) : ?>

		ecomm.i.push('<?php echo $item->getProduct()->getSku() ?>');
		ecomm.v.push('<?php echo $item->getProduct()->getFinalPrice() ?>');
		ecomm.p.push('<?php echo Mage::helper('core')->jsQuoteEscape($item->getProduct()->getName()) ?>');
		
	<?php endforeach ?>
	
	if (window.google_tag_params)
	{
		window.google_tag_params.ecomm_prodid 		= ecomm.i;
		window.google_tag_params.ecomm_pvalue		= ecomm.v;
		window.google_tag_params.ecomm_pname		= ecomm.p;
		window.google_tag_params.ecomm_pagetype 	= 'cart';
		window.google_tag_params.ecomm_totalvalue 	= '<?php echo $this->getQuote()->getGrandTotal() ?>';
	}
</script>