<?php
/** @var Mirasvit_Rma_Block_Adminhtml_Rma_Edit_Form $this */
/** @var Mage_Sales_Model_Order_Creditmemo $creditmemo */
$rma = $this->getRma();
$fieldForm = $this->getFieldForm();
$customerForm = $this->getCustomerForm();
$refundResolutionId = Mage::helper('rma')->getResolutionByCode('refund')->getId();
$isCreditEnabled = $this->getIsCreditEnabled();
?>

<script type="text/javascript">
    function isNumeric(obj) {
        return !jQuery.isArray( obj ) && (obj - parseFloat( obj ) + 1) >= 0;
    }

    function checkQtyOrdered(currentQty) {
        var ordered = parseInt($(currentQty.name.replace('qty_requested', 'qtyAvailable')).innerHTML.trim());
        var defaultQty = 0;
        if($('rma_id').value != '') {
         ordered += parseInt($(currentQty.name.replace('qty_requested', 'rma_item_qty')).value);
         defaultQty = ordered;
        }
        if(isNumeric(currentQty.value) && isNumeric(ordered)) {
            if(currentQty.value > ordered) {
                currentQty.value = defaultQty;
                alert("<?php echo $this->__('You can not return more, than available. Please, try again.') ?>");
            }
        }
    }
</script>

<form id="edit_form" action="<?php echo $this->getUrl('*/*/save') ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"/>
    <input name='rma_id' id='rma_id' value='<?php echo $rma->getId() ?>' type='hidden'>

    <div class="entry-edit">

        <?php if ($fieldForm): ?>
            <div class="box-left">
                <div class="entry-edit">
                    <?php echo $this->getGeneralInfoForm()->toHtml() ?>
                </div>
            </div>
            <div class="box-right">
                <div class="entry-edit">
                    <?php echo $fieldForm->toHtml() ?>
                </div>
            </div>

            <div class="clear"></div>
        <?php else: ?>
            <?php echo $this->getGeneralInfoForm()->toHtml() ?>
        <?php endif; ?>

        <?php echo $customerForm->toHtml() ?>

        <?php echo $this->getOrdersHtml() ?>
        <?php echo $this->getOfflineOrdersHtml() ?>

        <div class="box-left">
            <div class="entry-edit">
                <?php echo $this->getShippingAddressForm()->toHtml() ?>
            </div>
        </div>
        <?php if ($this->getExchangeNewAmount()): ?>
        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Exchange/Credit Balance') ?></h4>
                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset " id="field_fieldset">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                            <?php if ($this->getIsCreditEnabled()): ?>
                                <tr>
                                    <td class="label"><label><?php echo $this->__('Customer credit balance:')?></label></td>
                                    <td class="value">
                                        <b><?php echo Mage::helper('core')->currency($this->getCreditAmount(), true, false);?></b>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Total price of new products:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeNewAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Total price of exchanged/credit products:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeOldAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Price difference:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeDiffAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <?php if ($this->getExchangeDiffAmount() != 0 && $this->getIsCreditEnabled()): ?>
                                <tr>
                                    <td class="label"><label><?php echo $this->__('Resolution:')?></label></td>
                                    <td class="value">
                                        <select name="exchange_credit">
                                            <?php if ($this->getExchangeDiffAmount() > 0 && $this->getExchangeDiffAmount() < $this->getCreditAmount()): ?>
                                                <option value="0"><?php echo $this->__('Get %s from customer credit balance', Mage::helper('core')->currency($this->getExchangeDiffAmount(), true, false))?></option>
                                            <?php endif;
                                            if ($this->getExchangeDiffAmount() < 0): ?>
                                                <option value="1"><?php echo $this->__('Put %s to customer credit balance', Mage::helper('core')->currency(abs($this->getExchangeDiffAmount()), true, false))?></option>
                                            <?php endif; ?>
                                            <option value="3"><?php echo $this->__('Resolve manually')?></option>
                                        </select>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Return Address') ?></h4>

                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset " style="overflow: auto;">
                    <div class="hor-scroll">
                        <?php echo $this->getReturnAddressHtml() ?>
                        <?php echo $this->getFedExLabelHtml();?>
                    </div>

                </div>
            </div>
        </div>
        <?php echo $this->getFedExHtml(); ?>
        <div class="clear"></div>
        <?php if ($rma->getId()) : ?>
            <div class="box-left">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form"><?php echo $this->__('RMA History') ?></h4>

                        <div class="form-buttons">
                            <?php if ($rma->getIsAdminRead()): ?>
                                <button onclick="window.location='<?php echo $this->getMarkUrl(false) ?>'" type="button">
                                    <span><span><span><?php echo Mage::helper('adminhtml')->__('Mark as unread'); ?></span></span></span>
                                </button>
                            <?php else: ?>
                                <button onclick="window.location='<?php echo $this->getMarkUrl(true) ?>'" type="button">
                                    <span><span><span><?php echo Mage::helper('adminhtml')->__('Mark as read'); ?></span></span></span>
                                </button>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="fieldset">
                        <?php echo $this->getHistoryHtml() ?>
                    </div>
                </div>
            </div>
            <div class="box-right">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Add Message') ?></h4>

                        <div class="form-buttons"></div>
                    </div>
                    <div class="fieldset " id="edit_fieldset">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list" style="width:100%">
                                <tbody>
                                <tr>
                                    <td class="value">
								<span class="field-row">
									<label for="reply_type"><?php echo $this->__('Message Type') ?></label>
									<select id="reply_type" name="reply_type" class=" select">
                                        <option value="public"
                                                selected="selected"><?php echo $this->__('Message to Customer') ?></option>
                                        <option value="internal"><?php echo $this->__('Internal Note') ?></option>
                                    </select>
									<div id="rma_reply_note"></div>
								</span>
                                        <?php echo $this->getTemplateForm()->toHtml() ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="value">
                                        <?php echo $this->getEditorForm()->toHtml() ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="value">
                                        <input id="attachment" name="attachment[]" value="" class="multi" type="file"/>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        <?php endif; ?>
</form>

