<?php $accountId = Mage::getStoreConfig(Mage_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>
<script type="text/javascript">
	//<![CDATA[
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
	})();
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '<?=$accountId;?>']);
	_gaq.push(['_trackPageview']);
	//]]>
</script>