<div class="modal fade" id="onestepcheckout-login-popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">
					<div class="switch-form">
						<div class="hidden"><?php echo $this->__('Forgotten your password?'); ?></div>
						<div><?php echo $this->__('Login'); ?></div>
					</div>
				</h4>
			</div>
			<div class="modal-body">
				<div class="switch-form">
					<div class="hidden">
						<form id="onestepcheckout-forgot-form">
							<div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
							<div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
							<div id="onestepcheckout-forgot-success" style="display: none;">
								<?php echo $this->__('We have now sent you a new password to your email address. Click the link below to return to login.'); ?>
							</div>
							<div id="onestepcheckout-forgot-table">
								<p><?php echo $this->__('Enter your email below and we\'ll send you a new password by email.'); ?></p>
								<div class="form-group">
									<label for="id_onestepcheckout_email"><?php echo $this->__('Email address'); ?></label>
									<input type="text" class="input-text" name="onestepcheckout_email" id="id_onestepcheckout_email" />
								</div>
							</div>
						</form>
						<p style="margin-top: 10px;"><a href="javascript:void(0);" id="onestepcheckout-return-login-link"><?php echo $this->__('Return to login'); ?></a></p>
					</div>
					<div>
						<form id="onestepcheckout-login-form">
							<div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
							<div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
							<div id="onestepcheckout-login-table">
								<p><?php echo $this->__('Please login with your email address and password.'); ?></p>
								<div class="form-group">
									<label for="id_onestepcheckout_username"><?php echo $this->__('Email address'); ?></label>
									<input tabindex="100" type="text" class="input-text" name="onestepcheckout_username" id="id_onestepcheckout_username" />
								</div>
								<div class="form-group">
									<label for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?></label>
									<input type="password" tabindex="101" name="onestepcheckout_password" class="input-text" id="id_onestepcheckout_password" />
								</div>
								<p style="margin-top: 10px;"><a href="javascript:void(0);" id="onestepcheckout-forgot-password-link"><?php echo $this->__('Forgotten your password?'); ?></a></p>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<span class="switch-form">
					<span class="hidden"><button id="onestepcheckout-forgot-button" type="button"><?php echo $this->__('Send password'); ?></button></span>
					<span><button tabindex="102" id="onestepcheckout-login-button" type="button"><?php echo $this->__('Login'); ?></button></span>
				</span>
			</div>
		</div>
	</div>
</div>

<script>
	var onestepcheckout_login_popup;
	var login_popup;
	Event.observe(window, 'load', function() {
		var options = {
			forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure'=>true)); ?>',
			login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure'=>true)); ?>',
			translations: {
				invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
				email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
			}
		};
		onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
		login_popup = onestepcheckout_login_popup;
	});
	jQuery('#onestepcheckout-forgot-password-link, #onestepcheckout-return-login-link').click(function(){
		jQuery('.switch-form > div, .switch-form > span').each(function(){
			if(jQuery(this).hasClass('hidden')) {
				jQuery(this).show().removeClass('hidden');
			} else {
				jQuery(this).hide().addClass('hidden');
			}
		});
	});
</script>
