<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>

<table class="onestepcheckout-summary table table-striped">
    <thead>
    <tr>
        <th class="name"><?php echo $this->__('Product'); ?></th>
        <th class="qty"><?php echo $this->__('Qty'); ?></th>
        <th class="total"><?php echo $this->__('Subtotal'); ?></th>
    </tr>
    </thead>
    <?php foreach ($this->getItems() as $item): ?>
        <tr>
            <td class="name">
                <?php echo $item->getName(); ?>
                <?php if ($checkoutHelper->settings['show_custom_options']): ?>
                    <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                    <?php if (isset($options['options']) && count($options['options']) > 0): ?>
                        <ul class="onestepcheckout-custom-options">
                            <?php foreach ($options['options'] as $option): ?>
                                <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <?php if ($item->getProduct()->isConfigurable()): ?>

                        <?php
                        $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                        ?>

                        <?php if (is_array($configurable_options) && count($configurable_options) > 0): ?>
                            <ul class="onestepcheckout-custom-options list-unstyled">
                                <?php foreach ($configurable_options as $option): ?>
                                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>

                    <?php endif; ?>

                <?php endif; ?>
            </td>
            <td class="qty"><?php echo $item->getQty(); ?></td>
            <td class="total">
                <?php if ($checkoutHelper->settings['display_tax_included']): ?>
                    <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<table class="onestepcheckout-totals table table-striped">
    <?php
    $totalsArray = [
        'subtotal'     => null,
        'buckaroo_fee' => null,
        'shipping'     => null
    ];

    $totalsSortOrder = [
        0 => 'subtotal',
        1 => 'buckaroo_fee',
        2 => 'shipping'
    ];
    ?>
    <?php foreach ($this->getTotals() as $total): ?>
        <?php if (!$total->getTitle() || $total->getCode() == 'tax')
        {
            continue;
        } ?>
        <?php
        $fullInfo = $total->getFullInfo();

        if (!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
                ?>
                <tr>
                    <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td>
                    <td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
                </tr>
            <?php endforeach;
        endif;

        $grandTotal = null;
        if ($total->getCode() != 'grand_total')
        {
            if (!isset($totalsArray[$total->getCode()]) && array_search($total->getCode(), $totalsSortOrder) === false)
                $totalsSortOrder[] = $total->getCode();

            $totalsArray[strtolower(trim($total->getCode()))] = $total;
        }
        else
            $grandTotal = $total;

    endforeach;
    $totalsArray['grand_total'] = $grandTotal;
    $totalsSortOrder[] = 'grand_total';

    foreach ($totalsSortOrder as $index => $code):
        echo '<!-- '.$index.' :: '.$code.' -->';
        $data = $totalsArray[$code];
        unset($totalsArray[$code]);
        if (!is_null($data)):
            ?>
            <tr<?php if ($code == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                    <?php

                    $value = $data->getValue();

                    if ($code == 'subtotal')
                    {
                        $total_name = $this->__('Subtotal');
                    }
                    elseif ($code == 'shipping')
                    {
                        $total_name = $this->__('Shipping');
                        if ($checkoutHelper->settings['display_tax_included'])
                        {
                            $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                        }
                    }
                    elseif ($code == 'grand_total')
                    {
                        $total_name = $this->__('Grand total');
                    }
                    else
                    {
                        $total_name = $total->getTitle();
                    }

                    echo $total_name;

                    ?>
                </td>
                <td class="value">
                    <?php echo $this->helper('checkout')->formatPrice($value); ?>
                </td>
            </tr>
            <?php
        endif;
    endforeach; ?>
</table>
<script type="text/javascript">
    //<![CDATA[
    var total = <?php echo $this->getGrandTotal();?>;
    if (payment.reloadcallback)
    {
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', ['_secure' => true]); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
    //]]>
</script>
