<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    /* Count for timer calculation declared here */
    $count = 1;
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');

    /* Admin Controllers for timer are declared here */
    $countdownFormatting    = Mage::getStoreConfig('countdown/general/formating');
    $countdownDesign        = Mage::getStoreConfig('countdown/general/design');
    
    /* Admin Controllers for timer are declared here */
    $countdownIsActive      = Mage::getStoreConfig('countdown/general/activate');
    $countdownIsActiveTitle = Mage::getStoreConfig('countdown/general/heading');
    $countdownIsActiveDesc  = Mage::getStoreConfig('countdown/general/caption');
    $countdownTitle         = Mage::getStoreConfig('countdown/general/title');

    $countdownTitleDay  = Mage::getStoreConfig('countdown/general/days');
    $countdownTitleHour = Mage::getStoreConfig('countdown/general/hours');
    $countdownTitleMin  = Mage::getStoreConfig('countdown/general/mins');
    $countdownTitleSec  = Mage::getStoreConfig('countdown/general/sec');

    $colorDescription   = Mage::getStoreConfig('countdown/colors/caption'); //
    $colorCountdown     = Mage::getStoreConfig('countdown/colors/text'); //
    
    $colorHeader        = Mage::getStoreConfig('countdown/colors/title'); // first line - title above countdown
?>

<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    
<?php else: ?>
    
    <div class="category-products">
        
        <?php echo $this->getToolbarHtml() ?>

        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product):?>
                    <?php $toDate = $_product->getSpecialTODate(); ?>
                        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                            <?php // Product Image ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            <div class="product-shop">
                                <div class="f-fix">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                    <?php if($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>

                                    <?php echo $this->getPriceHtml($_product, true) ?>

                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                            <?php if ($toDate && $countdownIsActive): ?>

                                <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                                    <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                                    
                                        
                                    
                                        <?php
                                            $targetTime = strtotime(Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM');
                                            $startTime  = strtotime(Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))));
                                            $diff   = $targetTime - $startTime;
                                        ?>
                                    
                                    
                                        <?php if($diff > 0) : ?>
                                    
                                    
                                    
                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION 
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT) : ?>



                                                <div class="CountdownBase Text TextH4">
                                                    <div class="CountdownTextBasic">

                                                        <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                                                            <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                                                        <?php endif; ?>

                                                        <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>

                                                        <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage' && $countdownIsActiveDesc != 'hideall') : ?>
                                                            <?php /*<div class="clear"></div> */ ?>
                                                            <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                                <div class="days"><?php echo $countdownTitleDay?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                                <div class="hours"><?php echo $countdownTitleHour?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                                <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                                <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>

                                            <?php endif;?>


                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION WITH BACKGROUND
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT_BACKGROUND) : ?>


                                                <div class="CountdownBase Text">
                                                    <div class="CountdownTextBackground">

                                                        <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                                                            <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                                                        <?php endif; ?>

                                                        <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>

                                                        <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage' && $countdownIsActiveDesc != 'hideall') : ?>
                                                            <?php /*<div class="clear"></div> */ ?>
                                                            <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                                <div class="days"><?php echo $countdownTitleDay?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                                <div class="hours"><?php echo $countdownTitleHour?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                                <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                                <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>

                                            <?php endif; ?>



                                            <?php 
                                            /**
                                            * DIGITALS COUNTDOWN VERSION'S
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD  ||  $countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2): ?>

                                            <?php
//                                                $targetTime = strtotime(Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM');
//                                                $startTime  = strtotime(Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))));
//                                                $diff   = $targetTime - $startTime;
                                                $sec    = $diff % 60;
                                                $min    = floor($diff/60) % 60;
                                                $hours  = floor($diff/(60*60)) % 24;
                                                $days   = floor($diff/(60*60*24)) % 365;
                                            ?>
                                            <div class="CountdownBase Text TextH4">
                                                <div class="CountdownDigitsBasic">
                                                    <?php if($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') :?>
                                                    <div class="HeadingTitle" id="heading<?php echo $count; ?>" style="color:#<?php echo $colorHeader?>;"><?php echo $countdownTitle ?></div>
                                                    <?php endif; ?>

                                                    <?php
                                                        $displayFormat = false;
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "99.23:59:59";
                                                            $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "23:59:59";
                                                            $displayTime = ($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                        {
                                                            $displayFormat = "59:59";
                                                            $displayTime = ($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                        {
                                                            $displayFormat = "59";
                                                            $displayTime = ($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        {
                                                            $displayFormat = "99.23:59:59";
                                                            $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }
                                                    ?>

                                                    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD) : ?>
                                                    <span class="counter<?php echo $count; ?> counter-analog" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
                                                    <?php endif;?>
                                                    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2) : ?>
                                                    <span class="counter<?php echo $count; ?> counter-analog2" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
                                                    <?php endif;?>

                                                    <?php if($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage') :?>
                                                    <div class="description" style="color: #<?php echo $colorDescription?>;">
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                        <div class="days"><?php echo $countdownTitleDay?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                        <div class="hours"><?php echo $countdownTitleHour?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                        <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                        <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                        <?php endif; ?>
                                                    </div>
                                                    <?php endif;?>
                                                </div>
                                            </div>
                                            <script>
                                                $j('.counter<?php echo $count; ?>').counter();
                                            </script>
                                            <?php $count = $count + 1; ?>


                                        <?php endif; ?>
                                    
                                    
                                    <?php endif; ?>
                                    
                                    
                                <?php endif; ?>
                            <?php endif; ?>
                                    
                                    
                                        
                                        
                        <?php endif;?>

                                                
                                    
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                

                                    <?php if($_product->isSaleable()): ?>
                                        <p style="clear: both;"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                    <?php else: ?>
                                        <p class="availability out-of-stock" style="clear: both;"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>

                                    <div class="desc std">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                    </div>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                        <?php endif; ?>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                        <?php endif; ?>
                                    </ul>
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        

                                    <?php if ($toDate && $countdownIsActive): ?>

                                        <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                                            <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>

                                                <?php 
                                                /**
                                                * TEXT COUNTDOWN VERSION 
                                                */
                                                ?>

                                                <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT) : ?>



                                                    <script type="text/javascript">
                                                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                                                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                                                        start_date = Date.parse(start);
                                                        var dnow<?php echo $count; ?> = new Date(start_date);
                                                        if(CountStepper>0)
                                                            ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                                                        else
                                                            ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                                                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);


                                                        <?php
                                                            $displayFormat = false;
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='day'>%%D%%</span><span class='sep'>:</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                            {
                                                                $displayFormat = "<span class='sec'>%%S%%</span>";
                                                            }
                                                        ?>

                                                        <?php if($displayFormat) : ?>
                                                        DisplayFormat = "<?php echo $displayFormat;?>";
                                                        <?php endif;?>

                                                        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                                                        CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                                                        j++;
                                                    </script>
                                                    <?php $count = $count + 1; ?>

                                                <?php endif; ?>






                                                <?php 
                                                /**
                                                * TEXT COUNTDOWN VERSION WITH BACKGROUND
                                                */
                                                ?>

                                                <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT_BACKGROUND) : ?>



                                                    <script type="text/javascript">
                                                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                                                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                                                        start_date = Date.parse(start);
                                                        var dnow<?php echo $count; ?> = new Date(start_date);
                                                        if(CountStepper>0)
                                                            ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                                                        else
                                                            ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                                                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);


                                                        <?php
                                                            $displayFormat = false;
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='day'>%%D%%</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                            {
                                                                $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                            }else
                                                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                            {
                                                                $displayFormat = "<span class='sec'>%%S%%</span>";
                                                            }
                                                        ?>

                                                        <?php if($displayFormat) : ?>
                                                        DisplayFormat = "<?php echo $displayFormat;?>";
                                                        <?php endif;?>

                                                        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                                                        CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                                                        j++;
                                                    </script>
                                                    <?php $count = $count + 1; ?>

                                                <?php endif;?>



                                            <?php endif;?>                                                                            
                                        <?php endif;?>


                                    <?php endif; ?>

                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                </div>
                            </div>
                        </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>


        <?php else: ?>
        <?php // Grid Mode ?>

            
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount();?>
            
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php $toDate = $_product->getSpecialTODate();?>
                <?php if ($i++%$_columnCount==0): ?>
                    <ul class="products-grid">
                <?php endif ?>
                        
                        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                            
                            
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            
                            <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>

                            
                            
                            
                            

                            <?php if ($toDate && $countdownIsActive): ?>
                            
                                <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                                    <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                            
                                        <?php
                                            $targetTime = strtotime(Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM');
                                            $startTime  = strtotime(Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))));
                                            $diff   = $targetTime - $startTime;
                                        ?>
                            
                                        <?php if($diff > 0) : ?>

                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION 
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT) : ?>

                                                <div class="CountdownBase Text TextH4">
                                                    <div class="CountdownTextBasic">

                                                        <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                                                            <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                                                        <?php endif; ?>

                                                        <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>

                                                        <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage' && $countdownIsActiveDesc != 'hideall') : ?>
                                                            <?php /*<div class="clear"></div> */ ?>
                                                            <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                                <div class="days"><?php echo $countdownTitleDay?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                                <div class="hours"><?php echo $countdownTitleHour?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                                <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                                <?php endif; ?>
                                                                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                        $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                                <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>

                                            <?php endif;?>



                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION WITH BACKGROUND
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT_BACKGROUND) : ?>


                                                    <div class="CountdownBase Text">
                                                        <div class="CountdownTextBackground">

                                                            <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                                                                <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                                                            <?php endif; ?>

                                                            <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>

                                                            <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage' && $countdownIsActiveDesc != 'hideall') : ?>
                                                                <?php /*<div class="clear"></div> */ ?>
                                                                <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                                                                    <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                                    <div class="days"><?php echo $countdownTitleDay?></div>
                                                                    <?php endif; ?>
                                                                    <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                                    <div class="hours"><?php echo $countdownTitleHour?></div>
                                                                    <?php endif; ?>
                                                                    <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                                    <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                                    <?php endif; ?>
                                                                    <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                                    <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                                    <?php endif; ?>
                                                                </div>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>

                                            <?php endif; ?>




                                            <?php 
                                            /**
                                            * DIGITALS COUNTDOWN VERSION'S
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD  ||  $countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2): ?>

                                            <?php
    //                                            $targetTime = strtotime(Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM');
    //                                            $startTime  = strtotime(Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))));
    //                                            $diff   = $targetTime - $startTime;
                                                $sec    = $diff % 60;
                                                $min    = floor($diff/60) % 60;
                                                $hours  = floor($diff/(60*60)) % 24;
                                                $days   = floor($diff/(60*60*24)) % 365;
                                            ?>
                                            <div class="CountdownBase Text TextH4">
                                                <div class="CountdownDigitsBasic">
                                                    <?php if($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'listpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') :?>
                                                    <div class="HeadingTitle" id="heading<?php echo $count; ?>" style="color:#<?php echo $colorHeader?>;"><?php echo $countdownTitle ?></div>
                                                    <?php endif; ?>

                                                    <?php
                                                        $displayFormat = false;
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "99.23:59:59";
                                                            $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "23:59:59";
                                                            $displayTime = ($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                        {
                                                            $displayFormat = "59:59";
                                                            $displayTime = ($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                        {
                                                            $displayFormat = "59";
                                                            $displayTime = ($sec < 10 ? '0':'').$sec;
                                                        }else
                                                        {
                                                            $displayFormat = "99.23:59:59";
                                                            $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                                                        }
                                                    ?>

                                                    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD) : ?>
                                                    <span class="counter<?php echo $count; ?> counter-analog" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
                                                    <?php endif;?>
                                                    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2) : ?>
                                                    <span class="counter<?php echo $count; ?> counter-analog2" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
                                                    <?php endif;?>

                                                    <?php if($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'listpage') :?>
                                                    <div class="description" style="color: #<?php echo $colorDescription?>;">
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                                                        <div class="days"><?php echo $countdownTitleDay?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                                                        <div class="hours"><?php echo $countdownTitleHour?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                                                        <div class="minutes"><?php echo $countdownTitleMin?></div>
                                                        <?php endif; ?>
                                                        <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                                                    $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                                                        <div class="seconds"><?php echo $countdownTitleSec?></div>
                                                        <?php endif; ?>
                                                    </div>
                                                    <?php endif;?>
                                                </div>
                                            </div>
                                            <script>
                                                $j('.counter<?php echo $count; ?>').counter();
                                            </script>
                                            <?php $count = $count + 1; ?>

                                            <?php endif; ?>



                                            <?php endif; ?>
                                            
                                            
                                        <?php endif; ?>
                                    <?php endif; ?>
                            
                            
                            
                            <?php endif;?>













                                                        <div class="actions">

                                                            <?php if($_product->isSaleable()): ?>
                                                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                                            <?php else: ?>
                                                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                            <?php endif; ?>







                                <?php if ($toDate && $countdownIsActive): ?>
                                    <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                                        <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>


                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION 
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT) : ?>

                                                <script type="text/javascript">
                                                    var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                                                    start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                                                    start_date = Date.parse(start);
                                                    var dnow<?php echo $count; ?> = new Date(start_date);
                                                    if(CountStepper>0)
                                                        ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                                                    else
                                                        ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                                                    gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);


                                                    <?php
                                                        $displayFormat = false;
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='day'>%%D%%</span><span class='sep'>:</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                        {
                                                            $displayFormat = "<span class='sec'>%%S%%</span>";
                                                        }
                                                    ?>

                                                    <?php if($displayFormat) : ?>
                                                    DisplayFormat = "<?php echo $displayFormat;?>";
                                                    <?php endif;?>

                                                    var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                                                    CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                                                    j++;
                                                </script>
                                                <?php $count = $count + 1; ?>
                                            <?php endif; ?>


                                            <?php 
                                            /**
                                            * TEXT COUNTDOWN VERSION WITH BACKGROUND
                                            */
                                            ?>

                                            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT_BACKGROUND) : ?>

                                                <script type="text/javascript">
                                                    var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                                                    start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                                                    start_date = Date.parse(start);
                                                    var dnow<?php echo $count; ?> = new Date(start_date);
                                                    if(CountStepper>0)
                                                        ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                                                    else
                                                        ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                                                    gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);


                                                    <?php
                                                        $displayFormat = false;
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='day'>%%D%%</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                                                        {
                                                            $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                                                        }else
                                                        if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                                                        {
                                                            $displayFormat = "<span class='sec'>%%S%%</span>";
                                                        }
                                                    ?>

                                                    <?php if($displayFormat) : ?>
                                                    DisplayFormat = "<?php echo $displayFormat;?>";
                                                    <?php endif;?>

                                                    var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                                                    CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                                                    j++;
                                                </script>
                                                <?php $count = $count + 1; ?>
                                            <?php endif;?>
                                                            
                                                                            


                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>

                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </li>
                <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>

    <?php endif; ?>
    
    <!--Dynamic style changes goes here-->
    <style>
        .products-grid .actions 
        {
            position: initial;
            bottom: initial;
        }        
    </style>
