<?php if ($this->displayBoth()):?>
<tr>
	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<?php echo $this->getExcludeTaxLabel() ?>
	</td>
	<td style="<?php echo $this->getStyle() ?>" class="a-right">
		<?php echo $this->helper('checkout')->formatPrice($this->getPaymentsFeeExcludeTax()) ?>
	</td>
</tr>
<tr>
	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<?php echo $this->getIncludeTaxLabel() ?>
	</td>
	<td style="<?php echo $this->getStyle() ?>" class="a-right">
		<?php echo $this->helper('checkout')->formatPrice($this->getPaymentsFeeIncludeTax()) ?>
	</td>
</tr>
<?php elseif($this->displayIncludeTax()) : ?>
<tr>
	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<?php echo $this->getTotal()->getTitle() ?>
	</td>
	<td style="<?php echo $this->getStyle() ?>" class="a-right">
		<?php echo $this->helper('checkout')->formatPrice($this->getPaymentsFeeIncludeTax()) ?>
	</td>
</tr>
<?php else:?>
<tr>
	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<?php echo $this->getTotal()->getTitle() ?>
	</td>
	<td style="<?php echo $this->getStyle() ?>" class="a-right">
		<?php echo $this->helper('checkout')->formatPrice($this->getPaymentsFeeExcludeTax()) ?>
	</td>
</tr>
<?php endif;?>