<?php
/**
 * Created by PhpStorm.
 * User: mathijs
 * Date: 29-11-17
 * Time: 11:13
 */ 
class Twm_ExtendAwPoints_Helper_Points_Config extends AW_Points_Helper_Config
{
    public function isPointsEnabled($storeId = null)
    {
        return Mage::helper('pointsandrewards')->isClubJmaMember() && parent::isPointsEnabled($storeId); // TODO: Change the autogenerated stub
    }
}