<div class="page-title">
    <h1>We hebben je geboortedatum nodig!</h1>
</div>
<div>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('twm_requestdob')->toHtml(); ?>
</div>
<div style="text-align: center; margin-top: 25px">
    <form method="post" action="<?php echo $this->getUrl('*/*/save');?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <select name="day" style="width: auto !important; display: inline-block !important">
            <?php
            for ($day = 1; $day <= 31; $day++):
            ?>
            <option value="<?php echo $day?>"><?php echo str_pad($day, 2, 0, STR_PAD_LEFT);?></option>
            <?php
            endfor;
            ?>
        </select>
        <select name="month" style="width: auto !important; display: inline-block !important">
            <option value="1">Januari</option>
            <option value="2">Februari</option>
            <option value="3">Maart</option>
            <option value="4">April</option>
            <option value="5">Mei</option>
            <option value="6">Juni</option>
            <option value="7">Juli</option>
            <option value="8">Augustus</option>
            <option value="9">September</option>
            <option value="10">Oktober</option>
            <option value="11">November</option>
            <option value="12">December</option>
        </select>
        <select name="year" style="width: auto !important; display: inline-block !important">
        <?php
        for ($year = 1900; $year <= date('Y'); $year++):
            ?>
            <option value="<?php echo $year?>"<?php if ($year == 1985):?> selected<?php endif;?>><?php echo $year;?></option>
            <?php
        endfor;
        ?>
        </select>
        <button class="button" type="submit" title="Sla mijn gegevens op">Sla mijn gegevens op</button>
    </form>
</div>