<?php $items = $this->getItems(); ?>
<?php $var = $this->getVarModel();?>
<?php $helper = Mage::helper('mtemail');?>
<table
    width="100%"
    style="width:100% !important;"
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td   style="font-size: 15px; line-height: 26px; color: #707582;">
            <table border="0" width="100%" cellspacing="0" cellpadding="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                <tr
                    <?php echo $var->getHtmlAttribute('style', 'order_item_name_head_style_bg', 'background-color: #e26a0a;'); ?>
                    <?php echo $var->getHtmlAttribute('bgcolor', 'order_item_name_head_bgcolor', '#e26a0a'); ?>
                    class="mteditor-bgcolor table-head-bg">
                    <td height="45"  width="2%"></td>
                    <td
                        <?php echo $var->getTextEditAttribute('order_item_name');?>
                        <?php echo $var->getHtmlAttribute('style', 'order_item_name_head_style', 'color: #ffffff; font-weight: bold; font-size: 14px;'); ?>
                        class="mteditor-color table-head-color"
                        height="45"  align="<?php echo $helper->isRTL()?'right':'left';?>">
                        <?php echo $var->getValue('order_item_name', "Item");?>

                    </td>
                    <td
                        <?php echo $var->getTextEditAttribute('order_item_qty');?>
                        <?php echo $var->getHtmlAttribute('style', 'order_item_qty_head_style', 'color: #ffffff; font-weight: bold;font-size: 14px;'); ?>
                        class="table-head-color"
                        height="45"  width="15%" align="center">
                        <?php echo $var->getValue('order_item_qty', "Qty");?>
                    </td>
                    <td
                        <?php echo $var->getTextEditAttribute('order_item_subtotal');?>
                        <?php echo $var->getHtmlAttribute('style', 'order_item_subtotal_head_style', 'color: #ffffff; font-weight: bold;font-size: 14px;'); ?>
                        class="table-head-color"
                        height="45"  width="15%" align="<?php echo $helper->isRTL()?'left':'right';?>">
                        <?php echo $var->getValue('order_item_subtotal', "Subtotal");?>
                    </td>
                    <td height="45"  width="2%"></td>

                </tr>
                <?php $i=0; foreach ($items as $_item): ?>
                    <?php if($_item->getParentItem()) continue; else $i++; ?>
                    <?php echo $this->getItemHtml($_item); ?>
                    <tr>
                         <td height="1"
                             <?php echo $var->getHtmlAttribute('style', 'order_item_line_style', 'background-color: #e26a0a; font-size:1px; line-height:1px; height:1px;'); ?>
                             <?php echo $var->getHtmlAttribute('bgcolor', 'order_item_line_bgcolor', '#e26a0a'); ?>
                             class="mteditor-bgcolor item-line-color"
                             colspan="6" ></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </td>
    </tr>

</table>
