<?php /* @var $this Mage_Checkout_Block_Onepage_Payment */ ?>

<form action="<?php echo Mage::getUrl('magejam/payment/save', array('_secure' => true)) ?>" id="co-payment-form" method="post">
    <input type="hidden" name="quote_id" value="<?php echo $this->getQuote()->getId() ?>">
    <?php echo $this->getChildHtml('methods') ?>
<footer>
    <em><?php echo $this->__('* Required Fields') ?></em>
    <button type="submit"><?php echo $this->__('Continue') ?></button>
</footer>
</form>
<script type="text/javascript">
    //<![CDATA[
    var form = new VarienForm('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    $('co-payment-form').down('UL').show();
    //]]>
</script>
