<?php
    /* Count for timer calculation declared here */
    $count = 1;
    $_product = $this->getProduct();
    $toDate = $_product->getSpecialTODate();

    $countdownFormatting    = Mage::getStoreConfig('countdown/general/formating');
    $countdownDesign        = Mage::getStoreConfig('countdown/general/design');
    
    /* Admin Controllers for timer are declared here */
    $countdownIsActive      = Mage::getStoreConfig('countdown/general/activate');
    $countdownIsActiveTitle = Mage::getStoreConfig('countdown/general/heading');
    $countdownIsActiveDesc  = Mage::getStoreConfig('countdown/general/caption');
    $countdownTitle         = Mage::getStoreConfig('countdown/general/title');

    $countdownTitleDay  = Mage::getStoreConfig('countdown/general/days');
    $countdownTitleHour = Mage::getStoreConfig('countdown/general/hours');
    $countdownTitleMin  = Mage::getStoreConfig('countdown/general/mins');
    $countdownTitleSec  = Mage::getStoreConfig('countdown/general/sec');

    $colorDescription   = Mage::getStoreConfig('countdown/colors/caption'); //
    $colorCountdown     = Mage::getStoreConfig('countdown/colors/text'); //
    
    $colorHeader        = Mage::getStoreConfig('countdown/colors/title'); // first line - title above countdown
?>


<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<?php /* <ul class="add-to-links"> */ ?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="addToFaves" style="padding-top: 10px;"> 
    <?php /* <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a> */ ?>
        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;"  class="btn secondary gae-click*Product-Page*PrForm*Add-To-Favorites LayoutAlign-Center" id="favorites"><?php echo $this->__('Add to Wishlist') ?></a>
    </div>
    <?php endif; ?>

<?php if ($toDate && $countdownIsActive): ?>

    <?php 
    /**
     * TEXT COUNTDOWN VERSION 
     */
    ?>

    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT) : ?>

    
        <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                    
            <div class="CountdownBase Text TextH4">
                <div class="CountdownTextBasic">

                    <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'viewpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                        <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                    <?php endif; ?>
                    
                    <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>
                    
                    <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'viewpage' && $countdownIsActiveDesc != 'hideall') : ?>
                        <?php /*<div class="clear"></div> */ ?>
                        <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                            <div class="days"><?php echo $countdownTitleDay?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                            <div class="hours"><?php echo $countdownTitleHour?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                            <div class="minutes"><?php echo $countdownTitleMin?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                            <div class="seconds"><?php echo $countdownTitleSec?></div>
                            <?php endif; ?>
                        </div>
               <?php endif; ?>
                </div>
            </div>
            <?php
            endif;
        endif; 
        ?>

            <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                    <script type="text/javascript">
                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                        start_date = Date.parse(start);
                        var dnow<?php echo $count; ?> = new Date(start_date);
                        if(CountStepper>0)
                            ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                        else
                            ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
                        

                        <?php
                            $displayFormat = false;
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                            {
                                $displayFormat = "<span class='day'>%%D%%</span><span class='sep'>:</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                            {
                                $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                            {
                                $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                            {
                                $displayFormat = "<span class='sec'>%%S%%</span>";
                            }
                        ?>
                        
                        <?php if($displayFormat) : ?>
                        DisplayFormat = "<?php echo $displayFormat;?>";
                        <?php endif;?>
                        
                        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                        CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                        j++;
                    </script>
                    <?php $count = $count + 1; ?>
                <?php endif;
            endif;
        ?>

    <?php endif;?>


    <?php 
    /**
     * TEXT COUNTDOWN VERSION WITH BACKGROUND
     */
    ?>

    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::TEXT_BACKGROUND) : ?>

    
        <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                    
            <div class="CountdownBase Text">
                <div class="CountdownTextBackground">

                    <?php if ($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'viewpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') : ?>
                        <div id="heading<?php echo $count; ?>" class="HeadingTitle" style="color:#<?php echo $colorHeader; ?>;"><?php echo $countdownTitle ?></div>
                    <?php endif; ?>
                    
                    <div id="countbox_<?php echo $count; ?>" class="Countdown" style="color: #<?php echo $colorCountdown;?>;"></div>
                    
                    <?php if ($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'viewpage' && $countdownIsActiveDesc != 'hideall') : ?>
                        <?php /*<div class="clear"></div> */ ?>
                        <div class="description" id="caption<?php echo $count; ?>" style="color: #<?php echo $colorDescription?>;">
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                            <div class="days"><?php echo $countdownTitleDay?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                            <div class="hours"><?php echo $countdownTitleHour?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                            <div class="minutes"><?php echo $countdownTitleMin?></div>
                            <?php endif; ?>
                            <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                                     $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                            <div class="seconds"><?php echo $countdownTitleSec?></div>
                            <?php endif; ?>
                        </div>
               <?php endif; ?>
                </div>
            </div>
            <?php
            endif;
        endif; 
        ?>

            <?php if ($_product->getPrice() > $_product->getSpecialPrice()) : ?>
                <?php if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                    <script type="text/javascript">
                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
                        start_date = Date.parse(start);
                        var dnow<?php echo $count; ?> = new Date(start_date);
                        if(CountStepper>0)
                            ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                        else
                            ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
                        

                        <?php
                            $displayFormat = false;
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                            {
                                $displayFormat = "<span class='day'>%%D%%</span><span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                            {
                                $displayFormat = "<span class='hour'>%%H%%</span><span class='sep'>:</span><span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                            {
                                $displayFormat = "<span class='min'>%%M%%</span><span class='sep'>:</span><span class='sec'>%%S%%</span>";
                            }else
                            if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                            {
                                $displayFormat = "<span class='sec'>%%S%%</span>";
                            }
                        ?>
                        
                        <?php if($displayFormat) : ?>
                        DisplayFormat = "<?php echo $displayFormat;?>";
                        <?php endif;?>
                        
                        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                        CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                        j++;
                    </script>
                    <?php $count = $count + 1; ?>
                <?php endif;
            endif;
        ?>

    <?php endif;?>



    <?php 
    /**
     * DIGITALS COUNTDOWN VERSION'S
     */
    ?>

    <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD  ||  $countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2): ?>

    <?php
        $targetTime = strtotime(Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM');
        $startTime  = strtotime(Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))));
        $diff   = $targetTime - $startTime;
        $sec    = $diff % 60;
        $min    = floor($diff/60) % 60;
        $hours  = floor($diff/(60*60)) % 24;
        $days   = floor($diff/(60*60*24)) % 365;
    ?>
    <div class="CountdownBase Text TextH4">
        <div class="CountdownDigitsBasic">
            <?php if($countdownIsActiveTitle == 'showall' || $countdownIsActiveTitle == 'viewpage' && $countdownIsActiveTitle != 'hideall' && $countdownTitle != '') :?>
            <div class="HeadingTitle" id="heading<?php echo $count; ?>" style="color:#<?php echo $colorHeader?>;"><?php echo $countdownTitle ?></div>
            <?php endif; ?>
            
            <?php
                $displayFormat = false;
                if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC)
                {
                    $displayFormat = "99.23:59:59";
                    $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                }else
                if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC)
                {
                    $displayFormat = "23:59:59";
                    $displayTime = ($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                }else
                if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC)
                {
                    $displayFormat = "59:59";
                    $displayTime = ($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                }else
                if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC)
                {
                    $displayFormat = "59";
                    $displayTime = ($sec < 10 ? '0':'').$sec;
                }else
                {
                    $displayFormat = "99.23:59:59";
                    $displayTime = ($days < 10 ? '0':'').$days.'.'.($hours < 10 ? '0':'').$hours.':'.($min < 10 ? '0':'').$min.':'.($sec < 10 ? '0':'').$sec;
                }
            ?>
            
            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD) : ?>
            <span class="counter counter-analog" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
            <?php endif;?>
            <?php if($countdownDesign == Iksanika_Countdown_Model_System_Config_Design::DIGITS_OLD2) : ?>
            <span class="counter counter-analog2" data-direction="down" data-format="<?php echo $displayFormat;?>"><?php echo $displayTime;?></span>
            <?php endif;?>
                
            <?php if($countdownIsActiveDesc == 'showall' || $countdownIsActiveDesc == 'viewpage') :?>
            <div class="description" style="color: #<?php echo $colorDescription?>;">
                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC) : ?>
                <div class="days"><?php echo $countdownTitleDay?></div>
                <?php endif; ?>
                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC) :?>
                <div class="hours"><?php echo $countdownTitleHour?></div>
                <?php endif; ?>
                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC) : ?>
                <div class="minutes"><?php echo $countdownTitleMin?></div>
                <?php endif; ?>
                <?php if($countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::DAYS_HOURS_MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::HOURS_MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::MIN_SEC ||
                            $countdownFormatting == Iksanika_Countdown_Model_System_Config_Formating::SEC) : ?>
                <div class="seconds"><?php echo $countdownTitleSec?></div>
                <?php endif; ?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <script>
        $j('.counter').counter();
    </script>
    <?php endif; ?>
<?php endif; ?>