<?php
/*
 * Slideshow.php
 * 
 * Copyright (c) 2012 Aftab Naveed <aftabnaveed@gmail.com>. 
 * 
 * This file is part of Displaze Web Services Inc..
 * 
 * Displaze Web Services Inc. is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Displaze Web Services Inc. is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Displaze Web Services Inc..  If not, see <http ://www.gnu.org/licenses/>.
 */

$_slideshow = $this->getSlideshow();
?>

</main>
</div>
</div>

<div id="carousel-example-generic" class="carousel carousel-wide slide" data-ride="carousel">

	<!-- Wrapper for slides -->
	<?php $i = 0; ?>
	<div class="carousel-inner" role="listbox">
		<?php foreach ($_slideshow as $_slide): ?>
		<div class="item<?php if($i == 0) { echo ' active'; } ?>" style="background-image: url(<?php echo Mage::helper('myslideshow')->getSlideshowUrl() . $_slide->getImage() ?>);">
			<a href="<?php echo $_slide->getUrl() ?>" alt="<?php $_slide->getTitle(); ?>" /></a>
		</div>
		<?php $i++; endforeach; ?>
	</div>

	<?php if ($i > 1): ?>
	<!-- Indicators -->
	<?php $i = 0; ?>
	<ol class="carousel-indicators">
		<?php foreach ($_slideshow as $_slide): ?>
		<li data-target="#carousel-example-generic" data-slide-to="<?php echo $i; ?>"<?php if($i == 0) { echo ' class="active"'; } ?>></li>
		<?php $i++; endforeach; ?>
	</ol>

	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
	<?php endif; ?>

</div>

<div class="container" id="home-container">
<div class="row">
<main class="col-md-12">