<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<?php echo $this->getCssJsHtml() ?>