<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Nostress
 * @package    Nostress_Nscexport
 * @copyright Copyright (c) 2012 NoStress Commerce (http://www.nostresscommerce.cz)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * @see  Nostress_Nscexport_Block_Adminhtml_Nscexport_Activation
 */
 ?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<div class="activation_form">
	<?php echo $this->getFormHtml() ?>
</div>
<div class="contact_form">
	<?php echo $this->getChildHtml('contactForm') ?>
</div>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
    contactForm = new varienForm('contact_form', '<?php echo $this->getValidationUrl() ?>');

	function addOverlay() 
	{
	   // create overlay and append to page
	   var overlay = document.createElement("div");
	   overlay.setAttribute("id","overlay");
	   overlay.setAttribute("class", "overlay");

	   elem = document.getElementById('anchor-content');
	   elem.appendChild(overlay);
	}
</script>
<?php echo $this->getFormScripts() ?>

<div id="loading-mask" style="display:none;">
    <p class="loader" id="loading_mask_loader">
    	<?php echo $this->__('Activation in progress.') ?><br/><?php echo $this->__('The process may take up to 30 seconds.') ?><br/><br/>
    	<img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__('Activation in progress.') ?>"/>
    </p>
</div>