<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @methods
 * - getValue($key, $default)
 * - getSelected($key, $value)
 * - getChecked($key)
 * - getAttributes()
 * - getMappings()
 * - getAddMapButtonHtml()
 * - getRemoveMapButtonHtml()
 */
?>

<script type="text/javascript">
 	function nscexportSubmit(url)
 	{
 		this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if(this.validator && this.validator.validate()){
            if(this.validationUrl){
                this._validate();
            }
            else{
                this._submit();
            }
            return true;
        }
        return false;
    };

	function getCategories(categoryProductsString)
	{
		var tmpCat = Array(); 
		if(!categoryProductsString || categoryProductsString == '')
			return tmpCat;

		var members = categoryProductsString.split('|');
		for (var i = 0; i < members.length; i++) 
		{
			var productIds = members[i].split(',');
			var catId = 0;
			for (var j = 0; j < productIds.length; j++) 
			{
				if(j == 0)
				{
					catId = productIds[j];
					tmpCat[catId] = Array();
				}
				else
				{
					tmpCat[catId].push(productIds[j]);
				}
			}
		}
		return tmpCat;
	};

//editForm = new editForm('edit_form');

//editForm.submit = function () 
//{
	//	while(1);
		//return false;
    	//this._submit();
        /*this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if (this.validator && this.validator.validate()) {
            if(this.validationUrl){
                this._validate();
            }
            else{
                this._submit();
            }
            displayLoadingMask();
            return true;
        }
        return false;*/
//};
</script>
<script type="text/javascript">
var profileImportOnly = ['profile_number_of_records', 'profile_decimal_separator'];
function showOption(select)
{
    select = $(select);
    for (var i = 0, l = select.options.length; i<l; i++) {
        $$('.'+select.id+'_'+select.options[i].value).each(function (el) {
            el.style.display = select.selectedIndex==i ? '' : 'none';
        });
    }

}

function addFieldMapping()
{
    var entityType = $('profile_entity_type').value;
    new Insertion.Bottom($('map_container_'+entityType), $('map_template_'+entityType).innerHTML);
}

function removeFieldMapping(button)
{
    Element.remove(button.parentNode);
}

function setMapFileField(select)
{
    select.parentNode.getElementsByTagName('input')[0].value = select.value;
}

function updateRun(select)
{
    if ($(select).value=='interactive') {
        $('file_list').show();
    } else {
        $('file_list').hide();
    }
}

Event.observe(window, 'load', function(){
    if($('profile_data_transfer')) {
        updateRun('profile_data_transfer');
    }
});
</script>
<?php     	
	$storeId = $this->getStore()->getId();
    Mage::register("nscexport_storeid",$storeId);
?>
    
<div class="entry-edit">
   	
     <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/save/id/'.$this->getRequest()->getParam('id'));?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />     
    <div id="profile-generator">
    <div class="entry-edit-head collapseable">
        <a id="nscexport_basic_settings-head" class="" href="#" onclick="Fieldset.toggleCollapse('nscexport_basic_settings', '<?php echo $this->getUrl('adminhtml/system_config/state/') ?>'); return false;"><?php echo $this->__("Export Profile Settings") ?>
        </a>
    </div>
    <input id="nscexport_basic_settings-state" name="config_state[nscexport_basic_settings]" type="hidden" value="1" />
    
    <fieldset id="nscexport_basic_settings" class="config collapseable" style="">
        <legend><?php echo $this->__("Export Profile Settings") ?></legend>      
        <input  type="hidden" id="store_id" name="store_id" value="<?php echo $storeId;    ?>"/>
        <span class="field-row">
            <label for="nscexport_store_label"><?php echo $this->__("Store-view").$this->__(":") ?> </label>
            <label id="nscexport_store_label"><?php echo $this->getStoreName($storeId); ?></label>
            <input class="input-text" id="nscexport_store" name="store_name" type="hidden" value="<?php echo $this->getStoreName($storeId); ?>" READONLY/>
        </span>           
        <span class="field-row">
            <label for="nscexport_profile_name"><?php echo $this->__("Profile Name").$this->__(":") ?> <span class="required">*</span></label>
            <input class="required-entry required-entry input-text" id="nscexport_profile_name" name="nscexport_profile_name" value="<?php echo $this->getValue('name') ?>"/>
        </span>                 
        <span class="field-row">
            <label for="nscexport_enabled"><?php echo $this->__("Enabled").$this->__(":") ?></label>
			<span class="with-tip">
	            <select id="nscexport_enabled" name="enabled" class="option-control">	                
	            	<option value="1" <?php echo $this->getSelected('enabled', '1'); ?> ><?php echo $this->__("Yes") ?></option>
	                <option value="0" <?php echo $this->getSelected('enabled', '0'); ?> ><?php echo $this->__("No") ?></option>	                
	            </select>				
			</span>
        </span>                           
        <span class="field-row">
            <label for="start_time"><?php echo $this->__("Start time").$this->__(":") ?></label> 
			<span class="with-tip">
         		<select id="nscexport_hour" name="start_time_hour" class="option-control" style="width:40px" >	                
	                <?php 
	                	for( $i=0;$i<24;$i++ ) 
	                	{
	                		$hour = str_pad($i, 2, '0', STR_PAD_LEFT);
	                		echo '<option value="'.$hour.'" '. $this->getSelected('start_time_hour',$i) .' >'.$hour . '</option>';
	                	}
	                ?>	                
	            </select>
	            :
	            <select id="nscexport_minute" name="start_time_minute" class="option-control" style="width:40px" >	                
	                <?php 
	                	for( $i=0;$i<60;$i++ ) 
	                	{
	                		$minute = str_pad($i, 2, '0', STR_PAD_LEFT);
	                		echo '<option value="'.$minute.'" '. $this->getSelected('start_time_minute',$i) .' >'.$minute . '</option>';
	                	}
	                ?>	                
	            </select>
	            :
	            <select id="nscexport_second" name="start_time_second" class="option-control" style="width:40px" >	                
	                <?php 
	                	for( $i=0;$i<60;$i++ ) 
	                	{
	                		$second = str_pad($i, 2, '0', STR_PAD_LEFT);
	                		echo '<option value="'.$second.'" '. $this->getSelected('start_time_second',$i) .' >'.$second . '</option>';
	                	}
	                ?>	                
	            </select>
                <small class="nscexport_start_time">
	                    <?php echo '('.$this->__("Hour").':'.$this->__("Minute").':'.$this->__("Second").')' ?>
	            </small>		         		
        	</span>          	     	 
        </span>         
        <span class="field-row">
            <label for="nscexport_frequency"><?php echo $this->__("Frequency").':' ?></label>
			<span class="with-tip">
         		<select id="nscexport_frequency" name="frequency" onchange="showFeildMapping();showOption(this)" class="option-control" >
	                <?php
	                	$freqItem = new Mage_Adminhtml_Model_System_Config_Source_Cron_Frequency();
      					$freqArr = $freqItem->toOptionArray();
      					foreach($freqArr as $value)
      					{
      						echo '<option value="'.$value['value'].'" ';
      						echo $this->getSelected('frequency', $value['value']);
      						echo ' >'.$this->__($value['label']).'</option>';      						
      					}
      				?>	                	                
	            </select>         			
        	</span>
        </span>                               
        <span class="field-row">
            <label for="nscexport_searchengine"><?php echo $this->__("Search engine").':' ?></label>
			<span class="with-tip">
	            <select id="nscexport_searchengine" name="searchengine" onchange="showOption(this)" class="option-control required-entry">	                
	                <?php
	                    $centrumIncluded = false;
	                    $engines = $this->getAllowedEnginesCollection();       
								
	                    echo '<option value="">'.$this->__("Please select").'</option>';
						foreach($engines as $code => $engine)
						{
							$engineName = $engine['title'];							 	
							if($code == "centrum")
								$centrumIncluded = true;
								
							echo '<option value="'.$code.'" ';
      						echo $this->getSelected('searchengine', $code);
      						echo ' >'.$this->__($engineName).'</option>'; 
						}
	                ?>	                	                
	            </select>				
			</span>
        </span>
        
        <?php 
        if($centrumIncluded)
        {
        	echo '<div class="nscexport_searchengine_centrum">
            		<span class="field-row">
                		<label for="centrumcategory">'.$this->__("Centrum category").':'.'</label>'.
        	  			'<select id="centrumcategory" name="centrumcategory" class="option-control">';
            $categories = Nostress_Nscexport_Helper_Data::getCentrumCategory();
        	foreach($categories as $keyvalue => $label)
			{
				echo '<option value="'.$keyvalue.'" ';
      			echo $this->getSelected('centrumcategory', $keyvalue);
      			echo ' >'.$this->__($label /*iconv("windows-1250", "UTF-8", $label)*/).' </option>'; 
			}
			echo 			'</select>
               			</span>            
        			</div>';
        }
        ?>         
        <span class="field-row">
            <label for="nscexport_filename"><?php echo $this->__("Export File Name").':' ?> <span class="required">*</span></label>
            <span class="with-tip">
            	<input class="required-entry required-entry input-text" id="nscexport_filename" name="filename" value="<?php echo $this->getFilename(); ?>"/>
        		<small><?php echo '('.$this->__('File Name without suffix - . xml or .csv will be added according to selected feed type.').')';?></small>         	
        	</span>
        </span>                        
    </fieldset>
	</div>  
	
	<div class="entry-edit-head collapseable">
	  	<a id="nscexport_categories_settings-head" class="" href="#" onclick="Fieldset.toggleCollapse('nscexport_categories_settings', '<?php echo $this->getUrl('adminhtml/system_config/state/') ?>'); return false;"><?php echo $this->__("Categories to export") ?>
	    </a>
	</div>
	<input id="nscexport_categories_settings-state" name="config_state[nscexport_categories_settings]" type="hidden" value="1" />
	<fieldset id="nscexport_categories_settings" class="config collapseable" style="">	    
		<div class="columns">
			<div id="page:left" class="side-col">
				<div class="categories-side-col">	
				    
				        <span class="field-row">
				          <input type="hidden" name="category_product_ids" id="product_categories" value="<?php echo $this->getCategoryProductsIds() ?>">
				        
				          <div id="product-categories" class="tree"></div>
				        </span>  
				   
			    </div>
			</div>
			<div id="content" class="main-col">
				<div class="main-col-inner">
					<div>
					<?php echo $this->getChildHtml('nscexportCatalogCategoryProducts'); ?>
					</div>
				</div>
			</div>
	    </div>
     </fieldset>
 	</form>
 </div>  

<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>
    <div class="no-display">
<form id="hidden_form" action=""></form>
</div>


<?php $myBlock = $this->getLayout()->getBlock('nscexportCatalogCategoryProducts'); ?>
   

<?php if($this->getRootNode() && $this->getRootNode()->hasChildren()): ?>

<script type="text/javascript"><!--
var cur_category = '<?php echo $this->getRootNode()->getId() ?>';
var cur_node = 0;
var categories = getCategories('<?php echo $this->getCategoryProductsIds() ?>');
var checkHandlerDisabled = false;

Ext.EventManager.onDocumentReady(function() {
    var categoryLoader = new Ext.tree.TreeLoader({
       dataUrl: '<?php echo $this->getLoadTreeUrl()?>'
    });

    categoryLoader.createNode = function(config) {
        config.uiProvider = Ext.tree.CheckboxNodeUI;
        var node;
        if (config.children && !config.children.length) {
            delete(config.children);
            node = new Ext.tree.AsyncTreeNode(config);

        } else {
            node = new Ext.tree.TreeNode(config);
        }
        return node;
    };

    categoryLoader.on("beforeload", function(treeLoader, node) {
        treeLoader.baseParams.category = node.attributes.id;
    });

    categoryLoader.on("load", function(treeLoader, node, config) {
        varienWindowOnload();
    });

    var tree = new Ext.tree.TreePanel('product-categories', {
        animate:false,
        loader: categoryLoader,
        enableDD:false,
        containerScroll: true,
		rootUIProvider: Ext.tree.CheckboxNodeUI,
		selModel: new Ext.tree.CheckNodeMultiSelectionModel(),
		rootVisible: '<?php echo $this->getRootNode()->getIsVisible() ?>'
	});
    tree.on('check', checkHandler, tree);
	// set the root node
    var root = new Ext.tree.TreeNode({
        text: '<?php echo $this->getRootNode()->getName() ?>',
        draggable:false,
        checked:'<?php echo $this->getRootNode()->getChecked() ?>',
        id:'<?php echo $this->getRootNode()->getId() ?>',
        uiProvider: Ext.tree.CheckboxNodeUI
    });

    tree.setRootNode(root);
	bildCategoryTree(root, <?php echo $this->getTreeJson() ?>);
    tree.addListener('click', categoryClick.createDelegate(this));

    // render the tree
    tree.render();
    root.expand();
    tree.expandAll();
    cur_node = root;
    relaodProductGrid(cur_node.id);
});

function bildCategoryTree(parent, config){
    if (!config) return null;

    if (parent && config && config.length){
        for (var i = 0; i < config.length; i++){
            config[i].uiProvider = Ext.tree.CheckboxNodeUI;
            var node;
            if (config[i].children && !config[i].children.length) {
                delete(config[i].children);
                node = new Ext.tree.AsyncTreeNode(config[i]);

            } else {
                node = new Ext.tree.TreeNode(config[i]);
            }
            parent.appendChild(node);
            node.loader = node.getOwnerTree().loader;
            if(config[i].children){
                bildCategoryTree(node, config[i].children);
            }
        }
    }
}

function addOrRemoveNode(node) 
{	
	if(cur_node != 0 && cur_node.id == node.id)
	{
		changeAllCheckboxesState(cur_node.attributes.checked);
		//if(cur_node.attributes.checked && !(cur_node.id in categories))
		//{
		//	addOrRemoveCategory(cur_category,false); 
		//	checkRelatedCategoryNode(false);
		//}
	}
	addOrRemoveCategory(node.id,node.attributes.checked);

	if(cur_node != 0 && cur_node.id == node.id && cur_node.attributes.checked)
	{
		if(cur_node.attributes.checked)
        	categories[cur_category] = getAllGridIds();
	}
};

function addOrRemoveCategory(categoryId,condition) 
{	
	if(condition) 
	{
    	categoryAdd(categoryId);
	} 
	else 
	{
    	categoryRemove(categoryId);
	}	
};


function categoryClick(node, e){
    //node.getUI().check(!node.getUI().checked())
    varienElementMethods.setHasChanges(Event.element(e), e);    
    cur_category = node.id;
    cur_node = node;
    relaodProductGrid(node.id);
};

function relaodProductGrid(id){

	var old = <?php echo $myBlock->getJsObjectName() ?>.reloadParams;
	
	if ( old.constructor.toString().indexOf("Array") == -1 ) {
		old = new Array();
	}
	
	var newparam = old.clone();
	var p = new String(id);
	
	<?php 
	// z nejakeho duvodu se nepamatuje filtr podle skupiny, nyni je zahrnut do url
	?>
	if( !<?php echo $myBlock->getJsObjectName() ?>.oldurl ) {
		<?php echo $myBlock->getJsObjectName() ?>.oldurl = <?php echo $myBlock->getJsObjectName() ?>.url;
	}
	<?php echo $myBlock->getJsObjectName() ?>.url = <?php echo $myBlock->getJsObjectName() ?>.oldurl + 'id/'+p + '/store/'+'<?php echo $storeId?>' +'/';
				
	<?php echo $myBlock->getJsObjectName() ?>.reloadParams = newparam;
	<?php echo $myBlock->getJsObjectName() ?>.reload(<?php echo $myBlock->getJsObjectName() ?>.url);
}

function categoryAdd(id) {

	if(!(id in categories))
		categories[id] = Array();
	else 
	{
		var curCat = categories[id];
		if(curCat[0] == 'deleted')
			categories[id] = Array();
	}
}
function categoryRemove(id) {
	if(id in categories)
		categories[id] = Array("deleted");
}

function checkHandler(node)
{
	if(checkHandlerDisabled)
		return; 
	addOrRemoveNode(node);
    if ( !node.isLeaf() && node.hasChildNodes() ) {
        this.removeListener('check', checkHandler);
        processChildren(node, node.attributes.checked);        
        this.on('check', checkHandler);
    }

	if(node.attributes.checked == true && categories[node.id].length == 0 && cur_node.id == node.id)
	{
		checkCategoryNode(node,false);
		addOrRemoveCategory(node.id,false); 
	}
}

function processChildren(node, state)
{	
    if ( !node.hasChildNodes() ) return false;
    for(var i = 0; i < node.childNodes.length; i++ ) {
        node.childNodes[i].ui.check(state);
        addOrRemoveNode(node.childNodes[i]);
        if ( node.childNodes[i].hasChildNodes() ) {
            processChildren(node.childNodes[i], state);
        }
    }
    return true;
}
--></script>
<?php endif; ?>

<script type="text/javascript">
    $$('.option-control').each(showOption);
    //changeEntityType();

    function showFeildMapping() {
    	//var direction = $('profile_direction').options[$('profile_direction').options.selectedIndex].value;
        var value = $('parse_fieldnames').options[$('parse_fieldnames').options.selectedIndex].value;
        var map = $('map_only_specified').options[$('map_only_specified').options.selectedIndex].value;

        if (direction == 'nscexport') {
	    	if (map) {
	    		Element.show($('__fieldmapping'));
	    	} else {
	    		deleteAllAddedMappingFields();
	    		Element.hide($('__fieldmapping'));
	    	}
        } else {
	        if (value) {
	            Element.hide($('__fieldmapping'));
	            deleteAllAddedMappingFields();
	        } else {
	            Element.show($('__fieldmapping'));
	        }
        }

    }

    function deleteAllAddedMappingFields()
    {
        var type = $('profile_entity_type').options[$('profile_entity_type').options.selectedIndex].value;

        var elems = $('map_container_'+type).childElements();
        if (elems.length > 0) for (var idx in elems) {
            if (elems[idx] != undefined && elems[idx].tagName != undefined) {
                elems[idx].remove();
            }
        }
    }
    

</script>

 <?php if( is_object($myBlock) && $myBlock->getJsObjectName() ): ?>
<script type="text/javascript"><!--
    var hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?> = '<?php echo $myBlock->getCheckboxesName(); ?>';
    $('hidden_form').innerHTML += '<div class="hidden"><input type="hidden" name="'+hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?>+'"  id="'+hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?>+'"  value=""/></div>';

    var checkBoxes<?php echo $myBlock->getJsObjectName() ?> = $H(<?php echo "";//$myBlock->vratPrirazeneIds(true) ?>);

    var warning = false;
    if (checkBoxes<?php echo $myBlock->getJsObjectName() ?>.size() > 0) {
        warning = true;
    }

    $(hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?>).value = checkBoxes<?php echo $myBlock->getJsObjectName() ?>.toQueryString();

    function addBox<?php echo $myBlock->getJsObjectName() ?>(grid, element, checked)
    {
    	
        if (checked) {
        	checkBoxes<?php echo $myBlock->getJsObjectName() ?>.set(element.value, 0);
        } else {
        	checkBoxes<?php echo $myBlock->getJsObjectName() ?>.unset(element.value);
        }
        $(hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?>).value = checkBoxes<?php echo $myBlock->getJsObjectName() ?>.toQueryString();
    	var a = new Array();
    	a[hidden_checkboxes_id<?php echo $myBlock->getJsObjectName() ?>+'[]'] = checkBoxes<?php echo $myBlock->getJsObjectName() ?>.keys();
    	grid.reloadParams = a;
    }

    function boxRowClick<?php echo $myBlock->getJsObjectName() ?>(grid, event)
    {
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if (trElement) {
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                if (checked) {
                   	checkbox[0].checked = true;
                    warning = false;
                } else {
                	checkbox[0].checked = false;
                }
                updateCategories(checkbox[0].value,checkbox[0].checked);
            }
        }
    }

    function boxRowInit<?php echo $myBlock->getJsObjectName() ?>(grid, row)
    {    
    	var mainCheckbox = document.getElementsByClassName('checkbox');
    	mainCheckbox[0].checked = false;
        if(cur_category in categories && categories[cur_category].length == 0)
        {
        	var ids = getAllGridIds();
        	if($('chosen_product_ids'))
        	{
            	categories[cur_category] = ids;
           	 	//var mainCheckbox = document.getElementsByClassName('checkbox');
      			//if(cur_node && cur_node.attributes)
      			//	mainCheckbox[0].checked = cur_node.attributes.checked ;
      			//else
      			//	mainCheckbox[0].checked = false;
  			}
        }
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        if (checkbox) 
        {
            
            if(cur_category in categories && categories[cur_category].indexOf(checkbox.value) != -1) {
        		checkbox.checked = true;
        	} else {
        		checkbox.checked = false;
        	}
        }
    }

    function myhandler<?php echo $myBlock->getJsObjectName() ?>(o)
    {
    	changeAllCheckboxesState(o.checked);
    }

    function changeAllCheckboxesState(condition)
    {

        	checkBoxes<?php echo $myBlock->getJsObjectName() ?>.each(function(el){
          		  el.checked = true
            });

            checkbox = document.getElementsByClassName('checkbox');
            for (i = 0; i < checkbox.length; i++) {
                checkbox[i].checked = condition ;
                if(checkbox[i].value != 'on')
                {
                	updateCategories(checkbox[i].value,checkbox[i].checked);
                }
                else if(checkbox.length == 1)
                	checkbox[i].checked = false;
                    
            }
	}
    
	function updateCategories(value,condition)
	{	
		if(condition)
		{
			addOrRemoveCategory(cur_category,true); 				
			checkRelatedCategoryNode(true);
			if(categories[cur_category].indexOf(value) == -1)
				categories[cur_category].push(value);
		}
		else
		{
			if(!(cur_category in categories))
				return;
			
			var index = categories[cur_category].indexOf(value);
			categories[cur_category].splice(index,1);
			if(categories[cur_category].length == 0)
			{
				addOrRemoveCategory(cur_category,false); 
				checkRelatedCategoryNode(false);
			}
		}
			
	}

	function checkRelatedCategoryNode(condition)
	{
		checkCategoryNode(cur_node,condition);
	}

	function checkCategoryNode(node,condition)
	{
		checkHandlerDisabled = true;
		node.getUI().check(condition);
		checkHandlerDisabled = false;
	}

	function getAllGridIds()
	{
		var ids = Array();
		if($('chosen_product_ids'))
			ids = $('chosen_product_ids').value.split(',');
		else
		{	
			var value = '<?php $this->getAllGridIds();?>';
			ids = value.split(',');
		}
		if(ids.length == 1 && ids[0]== "")
			ids = Array();
		return ids;
	}

	function updateOutput()
	{
		var result = "";
		var first = true;
		if(categories && categories.length > 0)
		{
			for (var key in categories) 
			{
				if(key && !isNaN(Number(key)))
				{
					if(first)
						first = false;
					else
					{
						result = result + '|';
					}
					result = result + key +','+ categories[key].join(',');
				}
			}
		}
		$('product_categories').value = result;
	}

	function updateOutputAndSave()
	{
		updateOutput();
		editForm.submit();
	}		
    
    <?php echo $myBlock->getJsObjectName() ?>.rowClickCallback = boxRowClick<?php echo $myBlock->getJsObjectName() ?>;
   <?php echo $myBlock->getJsObjectName() ?>.initRowCallback = boxRowInit<?php echo $myBlock->getJsObjectName() ?>;
   <?php echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = addBox<?php echo $myBlock->getJsObjectName() ?>;
   <?php echo $myBlock->getJsObjectName() ?>.checkCheckboxes = myhandler<?php echo $myBlock->getJsObjectName() ?>;
    <?php echo $myBlock->getJsObjectName() ?>.rows.each(function(row){boxRowInit<?php echo $myBlock->getJsObjectName() ?>(<?php echo $myBlock->getJsObjectName() ?>, row)});
--></script>
    <?php endif; ?>
