<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.4.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="page-title title-buttons">
    <h1><?php echo $this->__('Request RMA') ?></h1>
</div>
<div id="messages">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<form action="<?php echo $this->getUrl('awrma/guest_rma/checkorder') ?>" method="post" id="awrma-new-form">
    <fieldset>
        <h2 class="legend"><?php echo $this->__('Order Information') ?></h2>
		<div class="form-group">
                    <label for="awrma-orderid" class="required"><em>*</em><?php echo $this->__('Order Id') ?></label>
			<input type="text" name="orderid" id="awrma-orderid" class="form-control required-entry" />
                    </div>
		<div class="form-group">
                    <label for="awrma-email" class="required"><em>*</em><?php echo $this->__('E-mail') ?></label>
			<input type="text" name="email" id="awrma-email" class="form-control required-entry" />
                    </div>
    </fieldset>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Submit Request') ?>" class="btn btn-success button" id="awrma-new-submit"><span><span><?php echo $this->__('Submit Request') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    var awrmaNewForm = new VarienForm('awrma-new-form');
</script>