<ol>
<?php if (0 == $this->getDisplayType()): // default ?>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
            <?php else: echo $_item->getLabel() ?>
            <?php endif; ?>
            (<?php echo $_item->getCount() ?>)
        </li>
    <?php endforeach ?>
<?php elseif (1 == $this->getDisplayType()): // dropdown ?>
    <li>
        <select onchange="if (this.value) setLocation(this.value)" class="amshopby-select">
            <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
            <option value=""></option>
            <?php foreach ($this->getItems() as $_item): ?>
            <option  value="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?> (<?php echo $_item->getCount() ?>)</option>
            <?php endforeach ?>
        </select>
    </li>
<?php endif ?>
<?php if (Mage::getStoreConfig('amshopby/general/price_from_to')):?>
        <li>&nbsp;</li>
        <li>
            <input type="hidden" id="amshopby-price-url" value="<?php echo Mage::helper('amshopby')->getFullUrl(array('price'=>'price-from,price-to'))?>" />
            <input type="text" size="2" value="<?php echo $this->getPriceFrom()?>" name="price_from" class="input-text" id="amshopby-price-from" /> - 
            <input type="text" size="2" value="<?php echo $this->getPriceTo()?>" name="price_to" class="input-text" id="amshopby-price-to"/>
            <button type="submit" title="<?php echo $this->__('Find')?>" class="button amshopby-price-find" name="price_find" id="amshopby-price-btn"><span><span><?php echo $this->__('Find')?></span></span></button>
        </li> 
<?php endif ?>
</ol>