<?php
/**
 * @category    Transsmart
 * @package     Transsmart_Shipping
 * @copyright   Copyright (c) 2016 Techtwo Webdevelopment B.V. (http://www.techtwo.nl)
 */
?>
<?php /** @var Mage_Checkout_Block_Onepage_Progress $this */ ?>
<?php $_helper = Mage::helper('transsmart_shipping'); ?>
<?php $_quote = $this->getQuote(); ?>
<?php $_pickupLocation = Mage::helper('transsmart_shipping/pickupaddress')->getPickupAddressFromQuote($_quote); ?>

<?php if (!$_helper->isTranssmartQuote($_quote) || !$_pickupLocation): ?>
    <?php return ''; ?>
<?php endif; ?>

<br />
<br />
<div class="complete"  id="tss-ls-progress-pickup-header">
    <h3>
        <?php echo $_helper->__('Pickup Address'); ?>
    </h3>
</div>

<p class="complete" id="tss-ls-progress-pickup-content">
    <?php echo $_pickupLocation->format('html'); ?>
</p>

<a href="#shipping_method" onclick="checkout.changeSection('opc-shipping_method'); return false;" class="link"><?php echo $this->__('Change') ?></a>