<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Customsmtp
 * @version    1.0.8
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="box" style="padding:0;">
    <iframe id="aw-csmtp-body" frameborder="0" width="100%" onLoad="calcHeight();"  srcdoc="<?php echo htmlspecialchars($this->getMailBody()); ?>"></iframe>
    <script type="text/javascript">
        function calcHeight()
        {
            var bodyIframe = $('aw-csmtp-body');
            if (bodyIframe) {
                var bodyIframeHeight = bodyIframe.contentWindow.document.body.scrollHeight;
                bodyIframe.setAttribute('height', bodyIframeHeight);
            }
        }
    </script>
</div>