<?php $helperConfig = Mage::helper('points/config'); ?>
<?php if (Mage::helper('pointsandrewards')->canGetPoints()):?>
    <li class="control">
        <div class="input-box">
            <input id="club_jma" type="checkbox" name="club_jma" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for Club Je m\'appelle and receive %s %s as a Club Member!', $this->getPoints(), $helperConfig->getPointUnitName())); ?>" value="1" class="checkbox" />
        </div>
        <label for="club_jma"><?php echo $this->__('Sign up for Club Je m\'appelle and receive %s %s as a Club Member!', $this->getPoints(), $helperConfig->getPointUnitName()); ?></label>
    </li>
<?php else: ?>
    <li class="control">
        <div class="input-box">
            <input id="club_jma" type="checkbox" name="club_jma" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for Club Je m\'appelle')); ?>" value="1" class="checkbox" />
        </div>
        <label for="club_jma"><?php echo $this->__('Sign up for Club Je m\'appelle'); ?></label>
    </li>
<?php endif; ?>
