<?php
$helperConfig = Mage::helper('points/config');
?>
    <dt class="control">
        <input id="club_jma" type="checkbox" name="club_jma" title="<?php echo $this->__('Sign up for Club Je m\'appelle and receive %s %s (EUR %s) as a Club Member!', $this->getPoints(), $helperConfig->getPointUnitName(), $this->getMoney()); ?>" value="1" class="checkbox" />
        <label for="club_jma"><?php echo $this->__('Sign up for Club Je m\'appelle and receive %s %s (EUR %s) as a Club Member!', $this->getPoints(), $helperConfig->getPointUnitName(), $this->getMoney()); ?></label>
    </dt>
