<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Helpdeskultimate
 * @version    2.10.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-head">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_orders->getSize()): ?>
<table cellspacing="0" class="table table-striped" id="my-orders-table">
    <thead>
    <tr>
        <th><?php echo $this->__('Order #') ?></th>
        <th><?php echo $this->__('Date') ?></th>
        <th><?php echo $this->__('Ship to') ?></th>
        <th><?php echo $this->__('Order Total') ?></th>
        <th><?php echo $this->__('Order Status') ?></th>
    </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
    <tr>
        <td><?php echo $_order->getRealOrderId() ?></td>
        <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
        <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName())
                : '&nbsp;' ?></td>
        <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
        <td><em><?php echo $_order->getStatusLabel() ?></em></td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
<p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>