<?php
	$_code = $this->getMethodCode();
	$bank_select = $this->__('Select your bank');
?>
<ul class="docdata-form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<label for="<?php echo $_code ?>_issuer" class="required"><?php echo $bank_select ?><em>*</em></label>
		<div class="input-box">
			<select id="<?php echo $_code ?>_issuer"
					name="payment[issuer]"
					title="<?php echo $bank_select ?>"
					class="required-entry">
				<option value=""><?php echo $this->__('--Please Select--') ?></option>
			<?php foreach ($this->getIssuers() as $_key => $_issuer): ?>
				<option value="<?php echo $_issuer['id'] ?>"><?php echo $_issuer['name'] ?></option>
			<?php endforeach ?>
			</select>
		</div>
	</li>
</ul>	