<?php
/* @var $this Mirasvit_Rma_Block_Rma_View */

/* @var $rma Mirasvit_Rma_Model_Rma */
$rma = $this->getRma();
$customFields = Mage::helper('rma/field')->getVisibleCustomerCollection($this->getRma()->getStatusId(), false, true);
?>

<script>
    function rmaShowConfirmationForm()
    {
        $('rma-confirmation-form').show();
        $('rma-confirmation-form-overlay').show();
    }
    function rmaHideConfirmationForm()
    {
        $('rma-confirmation-form').hide();
        $('rma-confirmation-form-overlay').hide();
    }
</script>
<div class="rma-view">
    <div class="page-title">
        <h1><?php echo $this->__('RMA') ?> #<?php echo $rma->getIncrementId()?> - <?php echo $rma->getStatus()->getName() ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php if ($rma->getIsShowShippingBlock()): ?>
        <button onclick="var win = window.open('<?php echo $this->getPrintUrl()?>', '_blank');win.focus();" class="button pull-right"><span><span><?php echo $this->__('Print RMA Packing Slip')?></span></span></button>

        <?php if ($rma->getReturnLabel()): ?>
        <button onclick="var win = window.open('<?php echo $this->getPrintLabelUrl()?>', '_blank');win.focus();" class="button pull-right"><span><span><?php echo $this->__('Print RMA Shipping Label')?></span></span></button>
        <?php endif ?>

        <?php if ($this->getIsRequireShippingConfirmation()): ?>
            <button onclick="rmaShowConfirmationForm()" class="button pull-right"><span><span><?php echo $this->__('Confirm Shipping')?></span></span></button>

            <div id="rma-confirmation-form" class="rma-confirmation-form" style="display:none">
                <div class="close" onclick="rmaHideConfirmationForm();">×</div>
                <form action="<?php echo $this->getConfirmationUrl()?>" method="POST" enctype="multipart/form-data" id="rma-confirmation-form-validate" >
                    <?php echo $this->getBlockHtml('formkey')?>
                    <input name="guest_id" type="hidden" value="<?php echo $this->getRma()->getGuestId() ?>">
                    <h2 id="shipping-confirmation"><?php echo $this->getShippingConfirmation() ?></h2>

                    <ul class="form-list">
                        <?php foreach ($this->getShippingConfirmationFields() as $field): ?>
                        <li class="fields">
                            <div class="field">
                                <label for="<?php echo $field->getCode()?>" <?php if ($field->getIsRequiredCustomer()): ?>class="required"<?php endif ?>>
                                  <?php echo $this->__($field->getName()) ?>
                                  <?php if ($field->getIsRequiredCustomer()): ?>
                                  <em>*</em>
                                  <?php endif ?>
                                </label>
                                <div class="input-box">
                                    <?php echo Mage::helper('rma/field')->getInputHtml($field)?>
                                    <p class="rma-mute"><?php echo $field->getDescription() ?></p>
                                </div>
                            </div>
                        </li>
                        <?php endforeach; ?>
                        <li class="control buttons">
                            <button type="submit" title="<?php echo $this->__('Confirm Shipping') ?>" class="button"><span><span><?php echo $this->__('Confirm Shipping') ?></span></span></button>
                        </li>
                    </ul>
                </form>
            </div>

            <script type="text/javascript">
                var dataForm = new VarienForm('rma-confirmation-form', false);
            </script>
        <?php endif ?>
    <?php endif ?>

    <div class="fieldset">
        <h2 class="legend" id="request-information"><?php echo $this->__('Request Information') ?></h2>
        <table width="100%">
            <tr>
                <td width="50%" valign="top">
                    <table width="100%">
                        <tbody>
                            <tr>
                                <td><b><?php echo $this->__('RMA') ?>:</b></td>
                                <td class="rma-italic">
                                    #<?php echo $rma->getIncrementId() ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b><?php echo $this->__('Date Requested') ?>:</b>
                                </td>
                                <td class="rma-italic">
                                    <?php echo Mage::helper('core')->formatDate($rma->getCreatedAt(), 'medium') ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b><?php echo $this->__('Status') ?>:</b>
                                </td>
                                <td class="rma-italic">
                                    <?php echo Mage::helper('rma/locale')->getLocaleValue($rma->getStatus(), 'name') ?>
                                </td>
                            </tr>
                            <?php foreach ($this->getCustomFields() as $field): ?>
                            <?php if (!$value = Mage::helper('rma/field')->getValue($rma, $field)) {
    continue;
} ?>
                            <tr>
                                <td>
                                    <b><?php echo $this->__($field->getName()) ?>:</b>
                                </td>
                                <td class="rma-italic">
                                    <?php echo $value ?>
                                </td>
                            </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>

                </td>
                <td width="50%" valign="top">
<!--                    <b>--><?php //echo $this->__('Contact Information') ?><!--:</b>-->
<!--                    <div class="rma-italic">--><?php //echo $rma->getShippingAddressHtml() ?><!--</div>-->
                </td>
            </tr>
        </table>
    </div>

    <div class="fieldset">
        <h2 class="legend" id="items-rma-request-for"><?php echo $this->__('Items RMA Requested for') ?></h2>
        <table class="data-table" id="rma-table">
            <thead>
                <tr class="first last">
                    <th></th>
                    <th><?php echo $this->__('Product Name') ?></th>
                    <th><?php echo $this->__('Order') ?></th>
                    <th><?php echo $this->__('SKU') ?></th>
                    <th><?php echo $this->__('Price') ?></th>
                    <th><?php echo $this->__('Qty') ?></th>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerReasonRequired()): ?>
                        <th><?php echo $this->__('Reason') ?></th>
                    <?php endif; ?>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerConditionRequired()): ?>
                        <th><?php echo $this->__('Condition') ?></th>
                    <?php endif; ?>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerResolutionRequired()): ?>
                        <th><?php echo $this->__('Resolution') ?></th>
                    <?php endif; ?>
                    <?php if (count($customFields)): ?>
                        <th><?php echo $this->__('Additional') ?></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($rma->getItemCollection() as $item):?>
                <tr>
                    <td>
                        <?php if ($item->getProduct()): ?>
                            <img id="image" src="<?php echo $this->helper('catalog/image')->init($item->getProduct(), 'thumbnail')->resize(150) ?>" width="75px" />
                        <?php endif; ?>
                    </td>
                    <td><?php echo Mage::helper('rma')->getOrderItemLabel($item) ?></td>
                    <td>
                        <?php if ($item->getOrderId()): ?>
                            <?php echo Mage::helper('rma')->getOrderLabel($item->getOrderId(), $this->getOrderUrl($item->getOrderId()))?>
                        <?php else: ?>
                            <?php echo Mage::helper('rma')->getItemOrderLabel($item)?>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $item->getProductSku() ?></td>
                    <td><?php echo Mage::helper('rma')->getOrderItemPriceFormatted($item)  ?></td>
                    <td><?php echo $item->getQtyRequested() ?></td>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerReasonRequired()): ?>
                        <td class="rma-italic"><?php echo $this->__($item->getReasonName()) ?></td>
                    <?php endif; ?>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerConditionRequired()): ?>
                        <td class="rma-italic"><?php echo $this->__($item->getConditionName()) ?></td>
                    <?php endif; ?>
                    <?php if (Mage::helper('rma')->getConfig()->isCustomerResolutionRequired()): ?>
                        <td class="rma-italic">x<?php echo $this->__($item->getResolutionName()) ?></td>
                    <?php endif; ?>
                    <?php if (count($customFields)): ?>
                        <td>
                            <a href="#" onclick="event.preventDefault(); showCustomFields(this.parentNode)">Show/hide additional fields</a>
                            <?php $order = Mage::getModel('sales/order')->load($item->getOrderId()); ?>
                            <div class="custom-fields">
                                <?php foreach ($customFields as $field): ?>
                                    <div class="field">
                                        <label for="<?php echo $field->getCode()?>" <?php echo $field->getIsRequiredCustomer() ? 'class="required"><em>*</em>' : '>' ?><b><?php echo $this->__($field->getName()) ?></b>
                                        </label>
                                        <div class="input-box custom-field">
                                            <?php echo Mage::helper('rma/field')->getInputHtml($field, 'items[' . $order->getId() . '][' . $item->getOrderItemId() . ']' , $item)?>
                                            <p class="rma-mute"><?php echo $field->getDescription() ?></p>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php endforeach?>
                <?php foreach ($rma->getOfflineItemCollection() as $item):?>
                    <tr>
                        <td>

                        </td>
                        <td><?php echo $item->getName() ?></td>
                        <td>
                            <?php echo $item->getOfflineOrder()->getReceiptNumber() ?>
                        </td>
                        <td>-</td>
                        <td>-</td>
                        <td><?php echo $item->getQtyRequested() ?></td>
                        <?php if (Mage::helper('rma')->getConfig()->isCustomerReasonRequired()): ?>
                            <td class="rma-italic"><?php echo $this->__($item->getReasonName()) ?></td>
                        <?php endif; ?>
                        <?php if (Mage::helper('rma')->getConfig()->isCustomerConditionRequired()): ?>
                            <td class="rma-italic"><?php echo $this->__($item->getConditionName()) ?></td>
                        <?php endif; ?>
                        <?php if (Mage::helper('rma')->getConfig()->isCustomerResolutionRequired()): ?>
                            <td class="rma-italic"><?php echo $this->__($item->getResolutionName()) ?></td>
                        <?php endif; ?>
                        <?php if (count($customFields)): ?>
                            <td>
                                <a href="#" onclick="event.preventDefault(); showCustomFields(this.parentNode)">Show/hide additional fields</a>
                                <?php $orderId = $item->getOfflineOrder()->getId(); ?>
                                <div class="custom-fields">
                                    <?php foreach ($customFields as $field): ?>
                                        <div class="field">
                                            <label for="<?php echo $field->getCode()?>" <?php echo $field->getIsRequiredCustomer() ? 'class="required"><em>*</em>' : '>' ?><b><?php echo $this->__($field->getName()) ?></b>
                                            </label>
                                            <div class="input-box custom-field">
                                                <?php echo Mage::helper('rma/field')->getInputHtml($field, 'offline_items[' . $orderId . '][' . $item->getOrderItemId() . ']' , $item)?>
                                                <p class="rma-mute"><?php echo $field->getDescription() ?></p>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>

    <form action="<?php echo $this->getCommentPostUrl()?>" method="POST" enctype="multipart/form-data"    id="rma-form-validate" >
        <?php echo $this->getBlockHtml('formkey')?>
        <input name="id" type="hidden" value="<?php echo $this->getRma()->getId() ?>">
        <input name="guest_id" type="hidden" value="<?php echo $this->getRma()->getGuestId() ?>">

        <div class="fieldset">
            <h2 class="legend" id="add-comment"><?php echo $this->__('Add Comment') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="input-box">
                        <textarea name="comment" id="comment" class="input-text"></textarea>
                    </div>
                </li>

                <li class="fields">
                    <label for="attachment"><?php echo $this->__('Attach files') ?>
                    </label>
                    <div class="input-box">
                        <?php echo Mage::helper('mstcore/attachment')->getFileInputHtml(Mage::helper('rma/attachment')->getAllowedExtensions()) ?>
                    </div>
                    <?php echo Mage::helper('rma/attachment')->getAttachmentLimits() ?>
                </li>

                <?php foreach ($this->getCustomFields(true) as $field): ?>
                <li class="fields">
                    <div class="field">
                        <label id="customer-field" for="<?php echo $field->getCode()?>" <?php echo $field->getIsRequiredCustomer() ? 'class="required"><em>*</em>' : '>' ?><?php echo $this->__($field->getName()) ?></label>
                        <div class="input-box">
                            <?php echo Mage::helper('rma/field')->getInputHtml($field)?>
                            <p class="rma-mute"><?php echo $field->getDescription() ?></p>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>

            </ul>

            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"  onclick="dataFormSubmit(this)"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>

    <script type="text/javascript">
        var dataForm = new VarienForm('rma-form-validate', false);
        function dataFormSubmit(button){
            if(dataForm.validator &&  dataForm.validator.validate()){
                Form.Element.disable(button);
                dataForm.submit();
            }
        }
    </script>

    <?php if ($this->getCommentCollection()->count()): ?>
        <div class="fieldset rma-history">
            <h2 class="legend" id="rma-history"><?php echo $this->__('RMA History') ?></h2>

            <?php foreach ($this->getCommentCollection() as $comment):?>
            <div class="fieldset <?php if ($comment->getCustomerName()): ?>customer<?php else: ?>user<?php endif ?>">
                <h2 class="legend">
                    <?php if ($comment->getCustomerName()):?>
                        <?php echo $comment->getCustomerName() ?> |
                    <?php elseif ($comment->getUser()): ?>
                        <?php echo $comment->getUser()->getName() ?> |
                    <?php endif ?>

                    <?php echo Mage::helper('core')->formatDate($comment->getCreatedAt(), 'medium') ?> <?php echo Mage::helper('core')->formatTime($comment->getCreatedAt(), 'short') ?>
                </h2>

                <?php echo $comment->getTextHtml() ?>

                <?php if ($attachments = $comment->getAttachments()): ?>
                    <?php foreach ($attachments as $attachment): ?>
                        <br><a href="<?php echo $attachment->getUrl()?>"><?php echo $attachment->getName() ?></a>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
            <?php endforeach ?>
        </div>
    <?php endif ?>

<!--    --><?php //if ($rma->getCustomerId()): ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getListUrl()?>"><small>&laquo; </small><?php echo $this->__('Back to My Returns') ?></a></p>
    </div>
<!--    --><?php //endif ?>

    <div class="rma-confirmation-form-overlay" id="rma-confirmation-form-overlay" style="display:none;">&nbsp;</div>
</div>