<ol>
<?php
switch ($this->getDisplayType()){
    case 0: // labels only
        foreach ($this->getItemsAsArray() as $item)
			// $item['count'] 
            echo '<li><a class="'.$item['css'].'" href="#" onclick="window.location.href=\''.$item['url'].'\'">'. $item['label'] . '</a></li>';
    break;
    
    case 1: // images only
        echo '<li>';
        foreach ($this->getItemsAsArray() as $item)
            echo '<a href="'.$item['url'].'"><img src="'.$item['image'].'" title="'. $item['label'] .'" alt="'. $item['label'] .'"></a>';
        echo '</li>';
    break;
    
    case 2: // images and labels
        foreach ($this->getItemsAsArray() as $item){
            echo '<li><a class="'.$item['css'].'" href="'.$item['url'].'">';
            if (!empty($item['image'])){
                echo '<img src="'.$item['image'].'" title="'. $item['label'] .'" alt="'. $item['label'] .'">';
            }
            echo $item['label'] . '</a>' . $item['count'] . '</li>';
        }
    break;
    
    case 3: // dropdown
        echo '<li><select onchange="if (this.value) setLocation(this.value)" class="amshopby-select">';
        echo '<option value="">' . $this->getName() . '</option>';
        foreach ($this->getItemsAsArray() as $item)
            echo '<option '.$item['css'].' value="'.$item['url'].'">'. $item['label'] . $item['count'] . '</option>';
        echo '</select></li>';
    break;
    
    case 4: // 2 columns
        $items = $this->getItemsAsArray(); 
        $size  = sizeof($items);
        $half  =  ceil($size/2);
        
        echo '<li>';
        echo '<div class="amshopby-column">';
        for ($i=0; $i<$half; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count'] . '<br/>';
        }
        echo '</div>';
        echo '<div class="amshopby-column">';
        for ($i=$half; $i<$size; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count']. '<br/>';
        }
        echo '</div><div class="clearer">&nbsp;</div>';
        echo '</li>';
    break;
    case 5: // 3 columns
        $items = $this->getItemsAsArray();
        $size  = sizeof($items);
        $third  =  ceil($size/3);

        echo '<li class="column3">';
        echo '<div class="amshopby-column">';
        for ($i=0; $i<$third; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count'] . '<br/>';
        }
        echo '</div>';
        echo '<div class="amshopby-column">';
        for ($i=$third; $i<$third+$third; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count']. '<br/>';
        }
        echo '</div>';
		echo '<div class="amshopby-column">';
        for ($i=$third+$third; $i<$size; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count']. '<br/>';
        }
        echo '</div><div class="clearer">&nbsp;</div>';
        echo '</li>';
    break;
}
?>
</ol>