<?php $isTomatoes = strpos($_SERVER['SERVER_NAME'], 'tomatoes') !== false ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?php echo $this->pageTitle?></title>
    <base href="<?php echo $this->getSkinUrl()?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="*" />
    <style type="text/css">
        @font-face {
            font-family: 'LetterGothicMTStdRegular';
            src: url('/skin/frontend/twm/default/fonts/lettergothicmtstd-webfont.eot');
            src: url('/skin/frontend/twm/default/fonts/lettergothicmtstd-webfont.eot?#iefix') format('eot'),
            url('/skin/frontend/twm/default/fonts/lettergothicmtstd-webfont.woff') format('woff'),
            url('/skin/frontend/twm/default/fonts/lettergothicmtstd-webfont.ttf') format('truetype'),
            url('/skin/frontend/twm/default/fonts/lettergothicmtstd-webfont.svg#webfont9Uli7UaI') format('svg');
            font-weight: normal;
            font-style: normal;
        }
        h1 { font-weight:normal; }
        body { text-align: center; font-family:"LetterGothicMTStdRegular", sans-serif; text-transform: uppercase; margin-top:10%; }
        <?php if ($isTomatoes) : ?>
        body { color:#023e75; }
        <?php else : ?>
        body { color:#4c4c4c; }
        <?php endif ?>

    </style>
</head>
    <body>
        <?php require_once $contentTemplate; ?>
    </body>
</html>