<div class="amshopby-filters clearfix">
<?php
switch ($this->getDisplayType()){
    case 0: // labels only
        echo '<div class="custom-dropdown"><strong>'.$this->getName().'</strong><div class="list">';
        if ($this->getShowSearch()){
            echo '<div rel="search"><input type="text" class="amshopby_attr_search input-text" onkeyup="amshopby_attr_search(this)" /></div>';
        }
        foreach ($this->getItemsAsArray() as $item){
            echo '<a rel="'.$item['label'].'" '.(isset($item['style']) ? $item['style'] : '').' class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . $item['count'] . '</a>';
        }
        echo '</div></div>';
    break;
    
    case 1: // images only
        echo '<div>';
        foreach ($this->getItemsAsArray() as $item){
            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }
            echo '<a '.$item['style'].' class="'.$item['css'].'" href="'.$item['url'].'"><img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'"></a>';
            
        }
        echo '</div>';
    break;
    
    case 2: // images and labels
        if ($this->getShowSearch()){
            echo '<div rel="search"><input type="text" class="amshopby_attr_search" onkeyup="amshopby_attr_search(this)" /></div>';
        }
        foreach ($this->getItemsAsArray() as $item){
            echo '<div rel="'.$item['label'].'" '.$item['style'].'><a class="'.$item['css'].'" href="'.$item['url'].'">';
            
            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"'; 
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }
            
            if (!empty($item['image'])){
                echo '<img src="'.$item['image'].'" ' . $onHover . ' title="'. $item['label'] .'" alt="'. $item['label'] .'">';
            }
            echo $item['label'] . '</a>' . $item['count'] . '</div>';
        }
    break;
    
    case 3: // dropdown
        echo '<select onchange="if (this.value) setLocation(this.value)" class="amshopby-select amshopby-ajax-select">';
        echo '<option value="">' . $this->getName() . '</option>';
        //echo '<option value="'.$this->getRemoveUrl().'"></option>';
        foreach ($this->getItemsAsArray() as $item){
            echo '<option '.$item['css'].' value="'.$item['url'].'">'. $item['label'] . $item['count'] . '</option>';
        }
        echo '</select>';
    break;
    
    case 4: // 2 columns
        $items = $this->getItemsAsArray(); 
        $size  = sizeof($items);
        $half  =  ceil($size/2);
        
        echo '<div>';
        echo '<div class="amshopby-column">';
        for ($i=0; $i<$half; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count'] . '<br/>';
        }
        echo '</div>';
        echo '<div class="amshopby-column">';
        for ($i=$half; $i<$size; $i++){
            $item = $items[$i];
            echo '<a class="'.$item['css'].'" href="'.$item['url'].'">'. $item['label'] . '</a>' . $item['count']. '<br/>';
        }
        echo '</div>';
        echo '</div>';
    break;
}

if ($this->getDisplayType() < 3 && $this->getShowLessMore()){
    echo '<div class="amshopby-clearer"><a id="amshopby-more-'.$this->getRequestValue().'" class="amshopby-more" href="#">' . $this->__('More ...') . '</a></div>';
    echo '<div class="amshopby-clearer"><a id="amshopby-less-'.$this->getRequestValue().'" class="amshopby-less" href="#" style="display:none">' . $this->__('Less ...') . '</a></div>';
} 
?>
</div>
