<div class="amshopby-filters clearfix">
<?php if($this->canShowBlock()): ?>
    <?php echo $this->getStateHtml() ?>
    <?php if($this->canShowOptions()): ?>
        <?php foreach ($this->getFilters() as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <?php echo $_filter->getHtml() ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    <?php endif; ?>
    <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>"><?php echo Mage::helper('catalog')->__('Clear All') ?></a></div>
<?php else: ?>
<div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>
</div>
