<div class="amshopby-filters clearfix">
<?php if($this->canShowBlock()): ?>
    <?php echo $this->getStateHtml() ?>
    <?php if($this->canShowOptions()): ?>
        <?php foreach ($this->getFilters() as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <?php echo $_filter->getHtml() ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    <?php endif; ?>
    <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
    <?php endif; ?>
<?php else: ?>
<div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>
</div>
