<?php if($this->canShowBlock()): ?>
    <div class="amshopby-filters clearfix">
        <?php echo $this->getStateHtml() ?>

        <?php if($this->canShowOptions()): ?>
            <?php foreach ($this->getFilters() as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <?php echo $_filter->getHtml() ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
<?php else: ?>
<div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>