<?php $_code = Mage::app()->getRequest()->getParam('code'); ?>
<style>.embed-container { position: relative; padding-bottom: 46.25%; margin: 20px 0; height: 0; overflow: hidden; max-width: 100%; left: 50%; margin-left: -50%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=279492855531944&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="wrapper" style="background-color: #FFF; text-align: center;">
    <p>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo" style="padding-top: 20px;">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        </a>
    </p>
    <div class="container" id="main-container">
        <div class="row">
            <main class="col-md-4"></main>
            <main class="col-md-4">
                <div class='embed-container'>
                    <iframe src="https://player.vimeo.com/video/122101052?autoplay=1&color=ffffff&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
                <div class="fb-like" data-href="https://vimeo.com/122101052" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                <div class='embed-container' style="height:3500px">
                    <iframe src="//www.dhlparcel.nl/track-and-trace/<?php echo $_code ?>#main-content" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
             <main class="col-md-4"></main>
        </div>
    </div>
</div>
</div>